### ISSUE TITLE
Server Error (500) when trying to sync enterprise and federated users, and process group together

### ISSUE THREAD

**Issue by raymond-ensemble** [adobe-apiplatform/user-sync.py#116]
**Steps**
1. Set up AD with both enterpriseID users and federatedID users (@ensemble.ca = enterprise and @ensemble-systems.com = federated)
2. Add the config setting **user_identity_type: federatedID** under **dashboard:**
3. Run **python user-sync.pex --users group "CCE AD Group 1" --process-groups.** (Only the federatedID users will be added to the dashboard)
4. Remove **user_identity_type: federatedID** (So it would default to enterpriseID)
5. Run **python user-sync.pex --users group "CCE AD Group 1" --process-groups.** again. (The enterpriseID users will be added to the dashboard)
6. Add back the **user_identity_type: federatedID** under **dashboard:**
7. Run **python user-sync.pex --users group "CCE AD Group 1" --process-groups.** again.

**Results**
- I see a "ServerError: Server Error (500)"
[server error log.txt](https://github.com/adobe-apiplatform/user-sync.py/files/873636/server.error.log.txt)
- It seems I can only trigger this error with the --process-group argument.

Question.
Is it possible to sync both enterpriseID users and federatedID users from AD at the same time? Or does this need the user to add custom extension code in the config for it to work? It seems to only allow one user type per run.

[user-sync-config.txt](https://github.com/adobe-apiplatform/user-sync.py/files/873658/user-sync-config.txt)

**Comment by adobeDan** [comment]
@raymond-ensemble I don't think you attached the right log.  There is no 500 error reported in the log.  Also, consider the following:

Yes, it's possible, when using AD, to specify the identity type as a field in the user record.  In your connector-ldap.yml you need to define the parameter `user_identity_type_format` to have a value of the form `"{attribute}"` where `attribute` is the name of the field that has the user's identity type in it (`adobeID`, `enterpriseID`, or `federatedID`).  For example, consider this snippet from an ldap-config I used to test this feature against an AD:
```yaml
user_identity_type: "federatedID"
user_identity_type_format: "{physicalDeliveryOfficeName}"
```
This snippet says that the default identity type for users in the directory is federatedID, but that there is an attribute that will override the default and give the user's identity type.  (This happens to be the LDAP attribute name for what shows up in the `General` AD tab as the user's `Office`.)  If that field contains one of the allowed value for an identity type, that type will be used for the created user.

Specifying the default value for creating users has no effect on which users in the dashboard are being sync'd against.  There are option that do control that: in the `dashboard` section of your config, you can specify one or more of `exclude_identity_types` (whose value is a list of identity types to exclude), `exclude-users` (list of regexps to exclude matching users), or `exclude-groups` (list of dashboard groups whose members to exclude).  This feature is documented in the rc2 docs, but they are incorrect in that they suggest these parameters should go other than in the `dashboard` section.

Feel free to call me this afternoon if you want more info about this, but in any event please do post the logs that have the Server Error (and preferably the runs leading up to them) so I can figure out what's going on, thanks!

**Comment by raymond-ensemble** [comment]
It should be the correct log. At the very bottom of the file, it shows the 
`2017-03-27 12:56:11 13856 ERROR main - Unhandled exception
Traceback (most recent call last):
  File "c:\users\raymondf\.pex\install\user_sync-1.2rc2-py2-none-any.whl.f8ddbb45621af04445afc502d8a9ef65e0bf86fb\user_sync-1.2rc2-py2-none-any.whl\user_sync\app.py", line 363, in main
    begin_work(config_loader)
  File "c:\users\raymondf\.pex\install\user_sync-1.2rc2-py2-none-any.whl.f8ddbb45621af04445afc502d8a9ef65e0bf86fb\user_sync-1.2rc2-py2-none-any.whl\user_sync\app.py", line 209, in begin_work
    rule_processor.run(directory_groups, directory_connector, dashboard_connectors)
  File "c:\users\raymondf\.pex\install\user_sync-1.2rc2-py2-none-any.whl.f8ddbb45621af04445afc502d8a9ef65e0bf86fb\user_sync-1.2rc2-py2-none-any.whl\user_sync\rules.py", line 170, in run
    dashboard_connectors.execute_actions()
  File "c:\users\raymondf\.pex\install\user_sync-1.2rc2-py2-none-any.whl.f8ddbb45621af04445afc502d8a9ef65e0bf86fb\user_sync-1.2rc2-py2-none-any.whl\user_sync\rules.py", line 964, in execute_actions
    action_manager.flush()
  File "c:\users\raymondf\.pex\install\user_sync-1.2rc2-py2-none-any.whl.f8ddbb45621af04445afc502d8a9ef65e0bf86fb\user_sync-1.2rc2-py2-none-any.whl\user_sync\connector\dashboard.py", line 316, in flush
    _, sent, _ = self.connection.execute_queued()
  File "c:\users\raymondf\.pex\install\umapi_client-2.1-py2.py3-none-any.whl.7f1fe3dedd9b1d4569fd4b6c10464b5647f0c1aa\umapi_client-2.1-py2.py3-none-any.whl\umapi_client\connection.py", line 268, in execute_queued
    return self.execute_multiple([], immediate=True)
  File "c:\users\raymondf\.pex\install\umapi_client-2.1-py2.py3-none-any.whl.7f1fe3dedd9b1d4569fd4b6c10464b5647f0c1aa\umapi_client-2.1-py2.py3-none-any.whl\umapi_client\connection.py", line 320, in execute_multiple
    last_batch_completed += self._execute_batch(actions)
  File "c:\users\raymondf\.pex\install\umapi_client-2.1-py2.py3-none-any.whl.7f1fe3dedd9b1d4569fd4b6c10464b5647f0c1aa\umapi_client-2.1-py2.py3-none-any.whl\umapi_client\connection.py", line 341, in _execute_batch
    result = self.make_call("/action/%s" % self.org_id, wire_form)
  File "c:\users\raymondf\.pex\install\umapi_client-2.1-py2.py3-none-any.whl.7f1fe3dedd9b1d4569fd4b6c10464b5647f0c1aa\umapi_client-2.1-py2.py3-none-any.whl\umapi_client\connection.py", line 401, in make_call
    raise ServerError(result)
ServerError: Server error (500): {}
2017-03-27 12:56:11 13856 INFO main - ========== End Run (User Sync version: 1.2rc2) (Total time: 0:00:08)`

**Comment by adobeDan** [comment]
@raymond-ensemble Whoops!  Sorry!  I opened the wrong log! :)...

**Comment by adobeDan** [comment]
OK, so there is indeed a UMAPI server problem, here, but I don't think there's a user-sync problem.  It looks like the server is generating an error while either executing or generating the response for the batch of actions 13 through 18.  Notice that, just above the error trace, we get the server response to action 12:
```text
2017-03-27 12:56:10 13856 DEBUG requests.packages.urllib3.connectionpool - https://usermanagement.adobe.io:443 "POST /v2/usermanagement/action/210DB41957FFDC210A495E53@AdobeOrg HTTP/1.1" 200 212
2017-03-27 12:56:10 13856 ERROR dashboard.owning.action - Error requestID: action_12 code: "error.user.type_mismatch" message: "The user type requested for the invite does not match the claimed domain type"
```
and then we get the POST of actions 13 through 18, with an error response:
```text
2017-03-27 12:56:11 13856 DEBUG requests.packages.urllib3.connectionpool - https://usermanagement.adobe.io:443 "POST /v2/usermanagement/action/AD0F754C57FFF69A0A495E58@AdobeOrg HTTP/1.1" 500 2
```
I suspect, based on my experience investigating your earlier issue #114 that in fact the user is executing 13-18 correctly and then the error comes when it's generating the response.  When I look in the admin console, I can see that user cce7 has indeed been given Acrobat (as requested in action 18), which suggests that the batch of actions was processed and it was the response generation that caused the 500 error.  Issue #114 has the same behavior: the server gets an exception (500 error) while generating a response on a batch of actions that includes a mix of enterprise and federated users (as does this batch).  So I'm going to close this again as wontfix because we need to fix the server problem.  However, I am also going to file a separate bug against both user-sync and umapi-client that they need to gracefully fail (and possibly retry) when they get a server 500 error.
