### ISSUE TITLE
Request better error message for LDAP connect failure

### ISSUE THREAD

**Issue by phil-levy** [adobe-apiplatform/user-sync.py#133]
2017-04-03 15:13:03 14784 INFO connector.ldap - Connecting to: _LDAP host URL goes here_.  e.g. ldap://ldap.example.com using username: LDAP user goes here
2017-04-03 15:13:03 14784 ERROR main - Unhandled exception
Traceback (most recent call last):
  File "c:\users\plevy.adobenet\.pex\install\user_sync-2.0a1-py2-none-any.whl.0cd7e265e62cbd246d7d4298f9124133982abbb2\user_sync-2.0a1-py2-none-any.whl\user_sync\app.py", line 323, in main
    begin_work(config_loader)
  File "c:\users\plevy.adobenet\.pex\install\user_sync-2.0a1-py2-none-any.whl.0cd7e265e62cbd246d7d4298f9124133982abbb2\user_sync-2.0a1-py2-none-any.whl\user_sync\app.py", line 184, in begin_work
    directory_connector.initialize(directory_connector_options)
  File "c:\users\plevy.adobenet\.pex\install\user_sync-2.0a1-py2-none-any.whl.0cd7e265e62cbd246d7d4298f9124133982abbb2\user_sync-2.0a1-py2-none-any.whl\user_sync\connector\directory.py", line 41, in initialize
    self.state = self.implementation.connector_initialize(options)
  File "c:\users\plevy.adobenet\.pex\install\user_sync-2.0a1-py2-none-any.whl.0cd7e265e62cbd246d7d4298f9124133982abbb2\user_sync-2.0a1-py2-none-any.whl\user_sync\connector\directory_ldap.py", line 39, in connector_initialize
    connector = LDAPDirectoryConnector(options)
  File "c:\users\plevy.adobenet\.pex\install\user_sync-2.0a1-py2-none-any.whl.0cd7e265e62cbd246d7d4298f9124133982abbb2\user_sync-2.0a1-py2-none-any.whl\user_sync\connector\directory_ldap.py", line 92, in __init__
    connection = ldap.initialize(host)
  File "c:\users\plevy.adobenet\.pex\install\python_ldap-2.4.25-cp27-none-win_amd64.whl.cc1088afa5f9350311753af9f4361762c8c8784e\python_ldap-2.4.25-cp27-none-win_amd64.whl\ldap\functions.py", line 92, in initialize
    return LDAPObject(uri,trace_level,trace_file,trace_stack_limit)
  File "c:\users\plevy.adobenet\.pex\install\python_ldap-2.4.25-cp27-none-win_amd64.whl.cc1088afa5f9350311753af9f4361762c8c8784e\python_ldap-2.4.25-cp27-none-win_amd64.whl\ldap\ldapobject.py", line 77, in __init__
    self._l = ldap.functions._ldap_function_call(ldap._ldap_module_lock,_ldap.initialize,uri)
  File "c:\users\plevy.adobenet\.pex\install\python_ldap-2.4.25-cp27-none-win_amd64.whl.cc1088afa5f9350311753af9f4361762c8c8784e\python_ldap-2.4.25-cp27-none-win_amd64.whl\ldap\functions.py", line 64, in _ldap_function_call
    result = func(*args,**kwargs)
LDAPError: (2, 'No such file or directory')
2017-04-03 15:13:03 14784 INFO main - ========== End Run (User Sync version: 2.0a1) (Total time: 0:00:00)

**Comment by adobeDan** [comment]
@ianmak, @ensembledeanw Can one of you please take care of this?  Looks like we need to catch LDAP connection failures and rethrow an appropriate assertion exception.

**Comment by ianmak** [comment]
okay I'll take this on
