### ISSUE TITLE
user-sync v2.1.1rc2 won't start up on Windows

### ISSUE THREAD

**Issue by adobeDan** [adobe-apiplatform/user-sync.py#224]
Apparently the startup sequence for pycryptodome 3.4.6 under pex packaging on Windows use paths that are too long and there is an exception thrown at some point that looks like this:
```python
Traceback (most recent call last):
  File ".bootstrap\_pex\pex.py", line 333, in execute
  File ".bootstrap\_pex\pex.py", line 81, in _activate
  File ".bootstrap\_pex\environment.py", line 135, in activate
  File ".bootstrap\_pex\environment.py", line 179, in _activate
  File ".bootstrap\_pex\environment.py", line 124, in update_candidate_distributions
  File ".bootstrap\_pex\environment.py", line 110, in load_internal_cache
  File ".bootstrap\_pex\environment.py", line 97, in write_zipped_internal_cache
  File ".bootstrap\_pex\util.py", line 176, in cache_distribution
  File ".bootstrap\_pex\common.py", line 125, in safe_open
IOError: [Errno 2] No such file or directory: u'C:\\cygwin64\\home\\labuser\\.pex\\install\\pycryptodome-3.4.6-cp27-cp27m-win_amd64.whl.dfec9ea083dc290e772b10e484883917dbc3683d.8fa03d27e0cf433e99022223456388ce\\pycryptodome-3.4.6-cp27-cp27m-win_amd64.whl\\Crypto/SelfTest/Cipher/test_vectors/AES/CFB128KeySbox128.rsp'
```
The exact file that it breaks on varies, depending on the length of your windows home path directory.  It always seems to break on a mixed-mode filename (containing both backward and forward slashes), and Python support for long pathnames requires they contain only backslashes.

**Comment by adobeDan** [comment]
So it turns out our published workaround: set the Windows environment variable PEX_ROOT to `c:\pex` (or something else short) works even for the rc2 build.  Thanks @phil-levy for pointing that out!!  So I am going to reopen this bug, back out the version change we took for pycryptodome, and add something to the release notes saying that, due to the library change, it will be necessary to use the PEX_ROOT environment variable on Windows to get this release to run.
