### ISSUE TITLE
Unhandled exception in LDAP connector

### ISSUE THREAD

**Issue by chad-fox** [adobe-apiplatform/user-sync.py#233]
I'm getting the following error when attempting to setup a new instance for a separate domain: 

-

2017-06-15 09:09:59 2384 INFO config - Using main config file: user-sync-config.yml
2017-06-15 09:09:59 2384 INFO main - ========== Start Run (User Sync version: 2.1) ==============
2017-06-15 09:09:59 2384 INFO main - ------- Invocation parameters -------
2017-06-15 09:09:59 2384 INFO main - user-sync.pex -t
2017-06-15 09:09:59 2384 INFO main - -------------------------------------
2017-06-15 09:10:01 2384 INFO processor - ---------- Start Load from Directory -----------------------
2017-06-15 09:10:01 2384 ERROR main - Unhandled exception
Traceback (most recent call last):
  File "c:\user-sync.pex\install\user_sync-2.1-py2-none-any.whl.fa4c34d1dc170ed47d2293e859ef616253546b5a\user_sync-2.1-py2-none-any.whl\user_sync\app.py", line 345, in main
    begin_work(config_loader)
  File "c:\user-sync.pex\install\user_sync-2.1-py2-none-any.whl.fa4c34d1dc170ed47d2293e859ef616253546b5a\user_sync-2.1-py2-none-any.whl\user_sync\app.py", line 203, in begin_work
    rule_processor.run(directory_groups, directory_connector, umapi_connectors)
  File "c:\user-sync.pex\install\user_sync-2.1-py2-none-any.whl.fa4c34d1dc170ed47d2293e859ef616253546b5a\user_sync-2.1-py2-none-any.whl\user_sync\rules.py", line 147, in run
    self.read_desired_user_groups(directory_groups, directory_connector)
  File "c:\user-sync.pex\install\user_sync-2.1-py2-none-any.whl.fa4c34d1dc170ed47d2293e859ef616253546b5a\user_sync-2.1-py2-none-any.whl\user_sync\rules.py", line 285, in read_desired
_user_groups
    directory_users = directory_connector.load_users_and_groups(directory_groups, extended_attributes)
  File "c:\user-sync.pex\install\user_sync-2.1-py2-none-any.whl.fa4c34d1dc170ed47d2293e859ef616253546b5a\user_sync-2.1-py2-none-any.whl\user_sync\connector\directory.py", line 51, in
 load_users_and_groups
    return self.implementation.connector_load_users_and_groups(self.state, groups, extended_attributes)
  File "c:\user-sync.pex\install\user_sync-2.1-py2-none-any.whl.fa4c34d1dc170ed47d2293e859ef616253546b5a\user_sync-2.1-py2-none-any.whl\user_sync\connector\directory_ldap.py", line 5
2, in connector_load_users_and_groups
    return state.load_users_and_groups(groups, extended_attributes)
  File "c:\user-sync.pex\install\user_sync-2.1-py2-none-any.whl.fa4c34d1dc170ed47d2293e859ef616253546b5a\user_sync-2.1-py2-none-any.whl\user_sync\connector\directory_ldap.py", line 1
17, in load_users_and_groups
    for user_dn, user in self.iter_users(all_users_filter, extended_attributes):
  File "c:\user-sync.pex\install\user_sync-2.1-py2-none-any.whl.fa4c34d1dc170ed47d2293e859ef616253546b5a\user_sync-2.1-py2-none-any.whl\user_sync\connector\directory_ldap.py", line 2
56, in iter_users
    for dn, record in result_iter:
  File "c:\user-sync.pex\install\user_sync-2.1-py2-none-any.whl.fa4c34d1dc170ed47d2293e859ef616253546b5a\user_sync-2.1-py2-none-any.whl\user_sync\connector\directory_ldap.py", line 3
46, in iter_search_result
    result_type, response_data, _rmsgid, serverctrls = connection.result3(msgid)
  File "c:\user-sync.pex\install\python_ldap-2.4.25-cp27-none-win_amd64.whl.cc1088afa5f9350311753af9f4361762c8c8784e\python_ldap-2.4.25-cp27-none-win_amd64.whl\ldap\ldapobject.py", l
ine 514, in result3
    resp_ctrl_classes=resp_ctrl_classes
  File "c:\user-sync.pex\install\python_ldap-2.4.25-cp27-none-win_amd64.whl.cc1088afa5f9350311753af9f4361762c8c8784e\python_ldap-2.4.25-cp27-none-win_amd64.whl\ldap\ldapobject.py", l
ine 521, in result4
    ldap_result = self._ldap_call(self._l.result4,msgid,all,timeout,add_ctrls,add_intermediates,add_extop)
  File "c:\user-sync.pex\install\python_ldap-2.4.25-cp27-none-win_amd64.whl.cc1088afa5f9350311753af9f4361762c8c8784e\python_ldap-2.4.25-cp27-none-win_amd64.whl\ldap\ldapobject.py", l
ine 106, in _ldap_call
    result = func(*args,**kwargs)
2017-06-15 09:10:01 2384 INFO main - ========== End Run (User Sync version: 2.1) (Total time: 0:00:02) 

_

Let me know if you'd like me to send the full debug log.

**Comment by chad-fox** [comment]
Issue was domain controller related. After changing the DC I was able to successfully run a test sync.

**Comment by adobeDan** [comment]
@chad-fox thanks so much for the bug report.  I'm reopening this issue because really the LDAP connector should be catching all errors of this type and reporting them cleanly rather than crashing with a stacktrace.

**Comment by chad-fox** [comment]
Sounds good, thanks for taking a look @adobeDan.
