### ISSUE TITLE
Unhandled exception if username present in user file with no domain

### ISSUE THREAD

**Issue by phil-levy** [adobe-apiplatform/user-sync.py#25]
If syncing from a file where the file looks like this:

firstname,lastname,email,country,groups,type,user,domain
John,Smith,jsmith@domainxyz.us,US,"all_apps",federatedID,jsmith

then you get an unhandled exception (see below).  It should either take the domain from the email address or give a more reasonable error message.

2017-02-23 12:12:08 16808 ERROR main - Unhandled exception
Traceback (most recent call last):
  File "c:\users\...\.pex\install\user_sync-1.0rc1-py2-none-any.whl.ea43aaba8f06fbb809d14379ef8554f20ee5a174\user_sync-1.0rc1-py2-none-any.whl\user_sync\app.py", line 262, in main
    begin_work(config_loader)
  File "c:\users\...\.pex\install\user_sync-1.0rc1-py2-none-any.whl.ea43aaba8f06fbb809d14379ef8554f20ee5a174\user_sync-1.0rc1-py2-none-any.whl\user_sync\app.py", line 168, in begin_work
    rule_processor.run(directory_groups, directory_connector, dashboard_connectors)
  File "c:\users\...\.pex\install\user_sync-1.0rc1-py2-none-any.whl.ea43aaba8f06fbb809d14379ef8554f20ee5a174\user_sync-1.0rc1-py2-none-any.whl\user_sync\rules.py", line 84, in run
    self.read_desired_user_groups(directory_groups, directory_connector)
  File "c:\users\...\.pex\install\user_sync-1.0rc1-py2-none-any.whl.ea43aaba8f06fbb809d14379ef8554f20ee5a174\user_sync-1.0rc1-py2-none-any.whl\user_sync\rules.py", line 143, in read_desired_user_groups
    user_key = RuleProcessor.get_directory_user_key(directory_user)
  File "c:\users\...\.pex\install\user_sync-1.0rc1-py2-none-any.whl.ea43aaba8f06fbb809d14379ef8554f20ee5a174\user_sync-1.0rc1-py2-none-any.whl\user_sync\rules.py", line 555, in get_directory_user_key
    return RuleProcessor.get_user_key(directory_user['username'], directory_user['domain'], directory_user['email'])
  File "c:\users\...t\.pex\install\user_sync-1.0rc1-py2-none-any.whl.ea43aaba8f06fbb809d14379ef8554f20ee5a174\user_sync-1.0rc1-py2-none-any.whl\user_sync\rules.py", line 574, in get_user_key
    return username + ',' + domain
TypeError: cannot concatenate 'str' and 'NoneType' objects
2017-02-23 12:12:08 16808 INFO main - ========== End Run (Total time: 0:00:01) ===================

**Comment by adobeDan** [comment]
fixed in v1, waiting for merge to main.

**Comment by adobeDan** [comment]
reopen until we merge to main

**Comment by adobeDan** [comment]
fixed in v1, so closing, since that's our default branch.
