### ISSUE TITLE
UserSync Error

### ISSUE THREAD

**Issue by shaungarcia** [adobe-apiplatform/user-sync.py#271]
I'm reporting this on behalf of my customer.  Please advise.

"We've just noticed that our Adobe User Sync is showing API errors as follows below.
The last successful sync (when the script stops running for us) was 7.30pm last night (5th September) and when the script started running again at 7am we started getting the error.
Are you able to advise if there is a problem at the Adobe end ?"

2017-09-06 10:14:27 11062 INFO processor - ---------- Start Load from Directory -----------------------
2017-09-06 10:14:27 11062 INFO processor - Building work list...
2017-09-06 10:14:27 11062 INFO connector.ldap - Loading users...
2017-09-06 10:14:27 11062 INFO connector.ldap - Total users loaded: 289
2017-09-06 10:14:27 11062 INFO processor - Total directory users after filtering: 289
2017-09-06 10:14:27 11062 INFO processor - ---------- End Load from Directory (Total time: 0:00:00) ---
2017-09-06 10:14:27 11062 INFO processor - ---------- Start Sync Dashboard ----------------------------
2017-09-06 10:14:27 11062 INFO processor - Syncing owning...
2017-09-06 10:14:28 11062 WARNING umapi_client - UMAPI timeout...service unavailable (code 429 on try 1)
2017-09-06 10:14:28 11062 WARNING umapi_client - Next retry in 20 seconds...
2017-09-06 10:14:48 11062 WARNING umapi_client - UMAPI timeout...service unavailable (code 429 on try 2)
2017-09-06 10:14:48 11062 WARNING umapi_client - Next retry in 32 seconds...
2017-09-06 10:15:20 11062 WARNING umapi_client - UMAPI timeout...service unavailable (code 429 on try 3)
2017-09-06 10:15:20 11062 WARNING umapi_client - Next retry in 65 seconds...

**Comment by adobeDan** [comment]
Yes, this behavior indicates an issue on the Adobe side: typically it means that high traffic from other clients has temporarily overloaded the server, and it is returning a 429 code which instructs clients to retry after a pause.

These messages from the `umapi_client`, which is the module that User Sync relies on to do server communication, do not actually indicate an error.  Instead, they indicate that the client has received the 429 code and, as instructed, is waiting a while and then trying the call again.  It will do this retry sequence 5 times (waiting longer each time) before giving up, and if it gives up it will give an actual `ERROR` message indicating that the server is unavailable.  The snippet of log you copied here do not show this error message, and if things continued normally past these warning then, in fact, the sync succeeded.

Hope this helps, and thanks for asking.

**Comment by shaungarcia** [comment]
Hi Daniel,

Further comment from the customer below. Please advise?

--------------------

Hey Shaun

Sorry I should know better than to send only bits of logs!!

The sync is not succeeding it's failing because the server is unavailable and it gives up after 4 attempts.

Below is the full log of the last sync attempt.

2017-09-06 14:32:42 23893 INFO config - Using main config file: /path/to/user-sync-config.yml
2017-09-06 14:32:42 23893 INFO main - ========== Start Run =======================================
2017-09-06 14:32:42 23893 INFO connector.ldap - Connecting to: ldap://ldap.com.au using username: user
2017-09-06 14:32:42 23893 INFO connector.ldap - Connected
2017-09-06 14:32:42 23893 INFO dashboard.owning - Creating connection for org id: "AD69606253F74B440A4C98A2@AdobeOrg" using private key file: "/path/to/adobe_private.key"
2017-09-06 14:32:42 23893 INFO dashboard.owning - API initialized on: https://usermanagement.adobe.io/v2/usermanagement
2017-09-06 14:32:42 23893 INFO processor - ---------- Start Load from Directory -----------------------
2017-09-06 14:32:42 23893 INFO processor - Building work list...
2017-09-06 14:32:42 23893 INFO connector.ldap - Loading users...
2017-09-06 14:32:42 23893 INFO connector.ldap - Total users loaded: 289
2017-09-06 14:32:42 23893 INFO processor - Total directory users after filtering: 289
2017-09-06 14:32:42 23893 INFO processor - ---------- End Load from Directory (Total time: 0:00:00) ---
2017-09-06 14:32:42 23893 INFO processor - ---------- Start Sync Dashboard ----------------------------
2017-09-06 14:32:42 23893 INFO processor - Syncing owning...
2017-09-06 14:32:43 23893 WARNING umapi_client - UMAPI timeout...service unavailable (code 429 on try 1)
2017-09-06 14:32:43 23893 WARNING umapi_client - Next retry in 16 seconds...
2017-09-06 14:32:59 23893 WARNING umapi_client - UMAPI timeout...service unavailable (code 429 on try 2)
2017-09-06 14:32:59 23893 WARNING umapi_client - Next retry in 31 seconds...
2017-09-06 14:33:30 23893 WARNING umapi_client - UMAPI timeout...service unavailable (code 429 on try 3)
2017-09-06 14:33:30 23893 WARNING umapi_client - Next retry in 62 seconds...
2017-09-06 14:34:33 23893 WARNING umapi_client - UMAPI timeout...service unavailable (code 429 on try 4)
2017-09-06 14:34:33 23893 ERROR umapi_client - UMAPI timeout...giving up after 4 attempts (109 seconds).
2017-09-06 14:34:33 23893 ERROR main - Unhandled exception
Traceback (most recent call last):
  File "/root/.pex/install/user_sync-1.1.1-py2-none-any.whl.21a3a678dccecc3c248aaab94e34af462a77008d/user_sync-1.1.1-py2-none-any.whl/user_sync/app.py", line 270, in main
    begin_work(config_loader)
  File "/root/.pex/install/user_sync-1.1.1-py2-none-any.whl.21a3a678dccecc3c248aaab94e34af462a77008d/user_sync-1.1.1-py2-none-any.whl/user_sync/app.py", line 176, in begin_work
    rule_processor.run(directory_groups, directory_connector, dashboard_connectors)
  File "/root/.pex/install/user_sync-1.1.1-py2-none-any.whl.21a3a678dccecc3c248aaab94e34af462a77008d/user_sync-1.1.1-py2-none-any.whl/user_sync/rules.py", line 111, in run
    self.process_dashboard_users(dashboard_connectors)
  File "/root/.pex/install/user_sync-1.1.1-py2-none-any.whl.21a3a678dccecc3c248aaab94e34af462a77008d/user_sync-1.1.1-py2-none-any.whl/user_sync/rules.py", line 245, in process_dashboard_users
    owning_unprocessed_groups_by_user_key = self.update_dashboard_users_for_connector(owning_organization_info, dashboard_connectors.get_owning_connector())
  File "/root/.pex/install/user_sync-1.1.1-py2-none-any.whl.21a3a678dccecc3c248aaab94e34af462a77008d/user_sync-1.1.1-py2-none-any.whl/user_sync/rules.py", line 535, in update_dashboard_users_for_connector
    for dashboard_user in dashboard_connector.iter_users():
  File "/root/.pex/install/user_sync-1.1.1-py2-none-any.whl.21a3a678dccecc3c248aaab94e34af462a77008d/user_sync-1.1.1-py2-none-any.whl/user_sync/connector/dashboard.py", line 104, in iter_users
    for u in umapi_client.UsersQuery(self.connection):
  File "/root/.pex/install/umapi_client-2.0.3-py2.py3-none-any.whl.27fb02ed364b2eb12931a3425c557b9f3d7fbe82/umapi_client-2.0.3-py2.py3-none-any.whl/umapi_client/api.py", line 197, in next
    return self.query._next_item()
  File "/root/.pex/install/umapi_client-2.0.3-py2.py3-none-any.whl.27fb02ed364b2eb12931a3425c557b9f3d7fbe82/umapi_client-2.0.3-py2.py3-none-any.whl/umapi_client/api.py", line 181, in _next_item
   self._next_page()
  File "/root/.pex/install/umapi_client-2.0.3-py2.py3-none-any.whl.27fb02ed364b2eb12931a3425c557b9f3d7fbe82/umapi_client-2.0.3-py2.py3-none-any.whl/umapi_client/api.py", line 172, in _next_page
    self.url_params, self.query_params)
 File "/root/.pex/install/umapi_client-2.0.3-py2.py3-none-any.whl.27fb02ed364b2eb12931a3425c557b9f3d7fbe82/umapi_client-2.0.3-py2.py3-none-any.whl/umapi_client/connection.py", line 226, in query_multiple
    result = self.make_call(query_path)
  File "/root/.pex/install/umapi_client-2.0.3-py2.py3-none-any.whl.27fb02ed364b2eb12931a3425c557b9f3d7fbe82/umapi_client-2.0.3-py2.py3-none-any.whl/umapi_client/connection.py", line 417, in make_call
    raise UnavailableError(self.retry_max_attempts, total_time, result)
UnavailableError: Server unavailable: Made 4 attempts over 109 seconds
2017-09-06 14:34:33 23893 INFO main - ========== End Run (Total time: 0:01:51) ===================






Best Regards
________________________________
Shaun Garcia | Principal Customer Success Manager | Adobe |  +61 424 980 888 | shaun@adobe.com<mailto:shaun@adobe.com> | www.adobe.com.au<http://www.adobe.com.au/>

[cid:image001.png@01D3276E.67E60510]

**Comment by adobeDan** [comment]
The enterprise support team and I have been in touch with the engineering team and they are modifying throttling limits so as to address the issue.  Yours is by no means the only impacted customer.  Our apologies and I am expecting this will be addressed soon.

**Comment by shaungarcia** [comment]
Thanks Daniel.  Look forward to hearing back.

Best Regards
________________________________
Shaun Garcia | Principal Customer Success Manager | Adobe |  +61 424 980 888 | shaun@adobe.com<mailto:shaun@adobe.com> | www.adobe.com.au<http://www.adobe.com.au/>

[cid:image001.png@01D327B6.79DE9DC0]

**Comment by adobeDan** [comment]
The problem was resolved about 10am PT this morning.  Your customer's syncs should be working fine since then.  Please follow up if there are any issues.  Thanks!

**Comment by shaungarcia** [comment]
Great thanks for the quick turnaround on this.

Best Regards
________________________________
Shaun Garcia | Principal Customer Success Manager | Adobe |  +61 424 980 888 | shaun@adobe.com<mailto:shaun@adobe.com> | www.adobe.com.au<http://www.adobe.com.au/>

[cid:image001.png@01D327BD.0B371DA0]
