### ISSUE TITLE
WinError 3

### ISSUE THREAD

**Issue by MKCPC** [adobe-apiplatform/user-sync.py#308]
I'm having issues getting this to run on Windows.  I have tried using Python 2.7.14 & 3.6.3 along with using User-Sync version 2.3rc1 and 2.2.2 however when attempting to run the application I get the following error:

```
S:\AdobeUserSync>python user-sync.pex -h
Traceback (most recent call last):
  File ".bootstrap\_pex\pex.py", line 359, in execute
  File ".bootstrap\_pex\pex.py", line 87, in _activate
  File ".bootstrap\_pex\environment.py", line 135, in activate
  File ".bootstrap\_pex\environment.py", line 179, in _activate
  File ".bootstrap\_pex\environment.py", line 124, in update_candidate_distribut
ions
  File ".bootstrap\_pex\environment.py", line 110, in load_internal_cache
  File ".bootstrap\_pex\environment.py", line 97, in write_zipped_internal_cache

  File ".bootstrap\_pex\util.py", line 178, in cache_distribution
  File ".bootstrap\_pex\common.py", line 124, in safe_open
  File ".bootstrap\_pex\common.py", line 112, in safe_mkdir
  File "S:\Python36\lib\os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "S:\Python36\lib\os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "S:\Python36\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'S:\\
AdobeUserSync\\user-sync.pex\\install'
```

I have tried moving this application to C: along with trying it on a different machine and I still receive the same error.  I am running the application as administrator

**Comment by bajwa-adobe** [comment]
Did you set PEX_ROOT environment variable?

```
set PEX_ROOT=S:\pex
```

**Comment by MKCPC** [comment]
No i've been setting it to S:\AdobeUserSync\user-sync.pex as it says in the documentation - https://adobe-apiplatform.github.io/user-sync.py/en/success-guide/install_sync.html

I've changed the environmental variable to be S:\AdobeUserSync now and it's working just fine.  Thanks for your help.

**Comment by adobeDan** [comment]
@bajwa-adobe thanks for helping out.

@MKCPC thanks for bringing the typos and unclarity in the documentation to our attention!  I am marking this as a doc bug and assigning to one of our leads.  In future, if you are using Python 3.6.3 on Windows 10, you don't need to set the PEX_ROOT environment variable at all, because Py3 on Win10 has full support for long pathnames.

**Comment by adobeDan** [comment]
The docs have been updated with PR #310.
