### ISSUE TITLE
UST 2.2.2:  OSError: Cannot load native module 'Crypto.Cipher._raw_ecb'

### ISSUE THREAD

**Issue by bhunut-adobe** [adobe-apiplatform/user-sync.py#327]
Run into this issue with RHEL 7 and CentOS 7 with Python 3.6.4 installed.
No issue when running with python 2.7.5

> [vagrant@bslm-022 ust]$ python3.6 user-sync -v
Traceback (most recent call last):
  File "/home/vagrant/ust/user-sync/.bootstrap/_pex/pex.py", line 365, in execute
  File "/home/vagrant/ust/user-sync/.bootstrap/_pex/pex.py", line 293, in _wrap_coverage
  File "/home/vagrant/ust/user-sync/.bootstrap/_pex/pex.py", line 325, in _wrap_profiling
  File "/home/vagrant/ust/user-sync/.bootstrap/_pex/pex.py", line 408, in _execute
  File "/home/vagrant/ust/user-sync/.bootstrap/_pex/pex.py", line 466, in execute_entry
  File "/home/vagrant/ust/user-sync/.bootstrap/_pex/pex.py", line 471, in execute_module
  File "/usr/local/lib/python3.6/runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/vagrant/.pex/install/user_sync-2.2.2-py3-none-any.whl.bce2b656b3b4728d30e9d73b39999a647a992ec1/user_sync-2.2.2-py3-none-any.whl/user_sync/app.py", line 29, in <module>
    import user_sync.config
  File "/home/vagrant/.pex/install/user_sync-2.2.2-py3-none-any.whl.bce2b656b3b4728d30e9d73b39999a647a992ec1/user_sync-2.2.2-py3-none-any.whl/user_sync/config.py", line 32, in <module>
    import user_sync.rules
  File "/home/vagrant/.pex/install/user_sync-2.2.2-py3-none-any.whl.bce2b656b3b4728d30e9d73b39999a647a992ec1/user_sync-2.2.2-py3-none-any.whl/user_sync/rules.py", line 25, in <module>
    import user_sync.connector.umapi
  File "/home/vagrant/.pex/install/user_sync-2.2.2-py3-none-any.whl.bce2b656b3b4728d30e9d73b39999a647a992ec1/user_sync-2.2.2-py3-none-any.whl/user_sync/connector/umapi.py", line 28, in <module>
    from Crypto.PublicKey import RSA
  File "/home/vagrant/.pex/install/pycryptodome-3.4.7-cp36-cp36m-linux_x86_64.whl.dd422c6ed6f4bb2dfc6adbe5416f29819a98713f/pycryptodome-3.4.7-cp36-cp36m-linux_x86_64.whl/Crypto/PublicKey/RSA.py", line 38, in <module>
    from Crypto.IO import PKCS8, PEM
  File "/home/vagrant/.pex/install/pycryptodome-3.4.7-cp36-cp36m-linux_x86_64.whl.dd422c6ed6f4bb2dfc6adbe5416f29819a98713f/pycryptodome-3.4.7-cp36-cp36m-linux_x86_64.whl/Crypto/IO/PKCS8.py", line 44, in <module>
    from Crypto.IO._PBES import PBES1, PBES2, PbesError
  File "/home/vagrant/.pex/install/pycryptodome-3.4.7-cp36-cp36m-linux_x86_64.whl.dd422c6ed6f4bb2dfc6adbe5416f29819a98713f/pycryptodome-3.4.7-cp36-cp36m-linux_x86_64.whl/Crypto/IO/_PBES.py", line 44, in <module>
    from Crypto.Cipher import DES, ARC2, DES3, AES
  File "/home/vagrant/.pex/install/pycryptodome-3.4.7-cp36-cp36m-linux_x86_64.whl.dd422c6ed6f4bb2dfc6adbe5416f29819a98713f/pycryptodome-3.4.7-cp36-cp36m-linux_x86_64.whl/Crypto/Cipher/__init__.py", line 3, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "/home/vagrant/.pex/install/pycryptodome-3.4.7-cp36-cp36m-linux_x86_64.whl.dd422c6ed6f4bb2dfc6adbe5416f29819a98713f/pycryptodome-3.4.7-cp36-cp36m-linux_x86_64.whl/Crypto/Cipher/_mode_ecb.py", line 46, in <module>
    """
  File "/home/vagrant/.pex/install/pycryptodome-3.4.7-cp36-cp36m-linux_x86_64.whl.dd422c6ed6f4bb2dfc6adbe5416f29819a98713f/pycryptodome-3.4.7-cp36-cp36m-linux_x86_64.whl/Crypto/Util/_raw_api.py", line 189, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s'" % name)
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb'

**Comment by bhunut-adobe** [comment]
I got this error when using the following build release:
user-sync-v2.3rc3-centos7-py363.tar.gz
user-sync-v2.2.2-centos7-py362.tar.gz

Look like something is wrong with py363 build for centos7. If I build from source, I do not get any error. Tested this on 2.2.2 and latest code on v2 branch

**Comment by adobeDan** [comment]
Hmmmm.  I suspect this may have to do with latest security patches for Meltdown/Spectre.  Can you verify the version of pycryptodome that you are getting when you build from scratch?

**Comment by bhunut-adobe** [comment]
pycryptodome 3.4.7

**Comment by bhunut-adobe** [comment]
that is the latest version: https://pypi.python.org/pypi/pycryptodome

**Comment by adobeDan** [comment]
Very strange.  You get this error with both 2.3rc3 and 2.2.2, yes?  That doesn't sound like a problem with a single build.  Would you mind spinning up a fresh CentOS7 build and trying again?  I'll also try on my instance, which was recently patched.

**Comment by bhunut-adobe** [comment]
Same issue on fresh centos 7.2 and 7.4 with py3.6.4

**Comment by adobeDan** [comment]
Oh, duh.  You are running python 3.6.4.  The build was made with python 3.6.3.  Can you try running it with 3.6.3 and see if it works?

**Comment by adobeDan** [comment]
@bhunut-adobe Did you ever try with py 3.6.3?  I am doing new builds today and will use the latest available python.

**Comment by bhunut-adobe** [comment]
@adobeDan  I figured out the issue. The problem was with my altinstall of python. It was missing library and wasn't install correctly. I ended up following this guide and fixed the issue

https://danieleriksson.net/2017/02/08/how-to-install-latest-python-on-centos/

Tested 2.2.2 and 2.3 RC4 with py3.6.4 and it is working fine now.

**Comment by adobeDan** [comment]
Yay!  Going to close this out now.
