### ISSUE TITLE
user sync error

### ISSUE THREAD

**Issue by Tomomi99145** [adobe-apiplatform/user-sync.py#330]
Error is displayed when executing user-sync command.
Please tell me the solution.

Example of execution
↓
C:\user-sync>python C:\user-sync\user-sync.pex -v
Traceback (most recent call last):
  File "C:\user-sync\user-sync.pex\.bootstrap\_pex\pex.py", line 359, in execute
  File "C:\user-sync\user-sync.pex\.bootstrap\_pex\pex.py", line 87, in _activate
  File "C:\user-sync\user-sync.pex\.bootstrap\_pex\environment.py", line 135, in activate
  File "C:\user-sync\user-sync.pex\.bootstrap\_pex\environment.py", line 179, in _activate
  File "C:\user-sync\user-sync.pex\.bootstrap\_pex\environment.py", line 124, in update_candidate_distributions
  File "C:\user-sync\user-sync.pex\.bootstrap\_pex\environment.py", line 110, in load_internal_cache
  File "C:\user-sync\user-sync.pex\.bootstrap\_pex\environment.py", line 97, in write_zipped_internal_cache
  File "C:\user-sync\user-sync.pex\.bootstrap\_pex\util.py", line 178, in cache_distribution
  File "C:\user-sync\user-sync.pex\.bootstrap\_pex\common.py", line 125, in safe_open
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\user_sync.pex\\install\\pycryptodome-3.4.7-cp36-cp36m-win_amd64.whl.ef643e79769d061fe8a935f3dd3ed41...\\pycryptodome-3.4.7-cp36-cp36m-win_amd64.whl\\Crypto/SelfTest/PublicKey/test_vectors/ECC/ecc_p256_private_enc_aes128.pem'

**Comment by Luci2015** [comment]
If you are not using Windows 10, you need to create the  env variable named "PEX_ROOT", with the value of "C:\pex"

**Comment by adobeDan** [comment]
@Tomomi99145 As @Luci2015 explained, this is a known issue with py2.7 running on Win 10 or earlier.  The docs explain the fix in detail [here](https://adobe-apiplatform.github.io/user-sync.py/en/user-manual/setup_and_installation.html#system-requirements).  If you can switch to using py3.6 instead of py2.7 you will avoid this problem completely. Please let us know if you've gotten things working.

**Comment by Tomomi99145** [comment]
I solved the problem after creat env variable.
Thank you for your support

**Comment by adobeDan** [comment]
Great, thanks for the update.  Glad it's working for you!
