### ISSUE TITLE
Failed to exchange token

### ISSUE THREAD

**Issue by Tomomi99145** [adobe-apiplatform/user-sync.py#352]
Error is displayed when executing user-sync command.
Please tell me the solution.

Example of execution
↓

2018-05-08 14:06:02 2960 INFO main - ========== Start Run (User Sync version: 2.2.2) ============
2018-05-08 14:06:02 2960 INFO main - ------- Invocation parameters -------
2018-05-08 14:06:02 2960 INFO main - user-sync.pex -t --users all --user-filter XXXXXXXX --adobe-only-user-action exclude
2018-05-08 14:06:02 2960 INFO main - -------------------------------------
2018-05-08 14:06:04 2960 INFO processor - ---------- Start Load from Directory -----------------------
2018-05-08 14:06:04 2960 WARNING ldap - Skipping user with dn CN=dcaasadmin,CN=Users,DC=aooo,DC=online: empty email attribute (userPrincipalName)
2018-05-08 14:06:04 2960 INFO processor - ---------- End Load from Directory (Total time: 0:00:00) ---
2018-05-08 14:06:04 2960 INFO processor - ---------- Start Sync with UMAPI ---------------------------
2018-05-08 14:06:04 2960 ERROR main - Unhandled exception
Traceback (most recent call last):
  File "c:\pex\install\user_sync-2.2.2-py3-none-any.whl.56859f7b19ab6fcd1575d2fc52de777a8c4ead8c\user_sync-2.2.2-py3-none-any.whl\user_sync\app.py", line 362, in main
    begin_work(config_loader)
  File "c:\pex\install\user_sync-2.2.2-py3-none-any.whl.56859f7b19ab6fcd1575d2fc52de777a8c4ead8c\user_sync-2.2.2-py3-none-any.whl\user_sync\app.py", line 213, in begin_work
    rule_processor.run(directory_groups, directory_connector, umapi_connectors)
  File "c:\pex\install\user_sync-2.2.2-py3-none-any.whl.56859f7b19ab6fcd1575d2fc52de777a8c4ead8c\user_sync-2.2.2-py3-none-any.whl\user_sync\rules.py", line 175, in run
    self.sync_umapi_users(umapi_connectors)
  File "c:\pex\install\user_sync-2.2.2-py3-none-any.whl.56859f7b19ab6fcd1575d2fc52de777a8c4ead8c\user_sync-2.2.2-py3-none-any.whl\user_sync\rules.py", line 426, in sync_umapi_users
    primary_adds_by_user_key = self.update_umapi_users_for_connector(umapi_info, umapi_connector)
  File "c:\pex\install\user_sync-2.2.2-py3-none-any.whl.56859f7b19ab6fcd1575d2fc52de777a8c4ead8c\user_sync-2.2.2-py3-none-any.whl\user_sync\rules.py", line 744, in update_umapi_users_for_connector
    for umapi_user in umapi_connector.iter_users():
  File "c:\pex\install\user_sync-2.2.2-py3-none-any.whl.56859f7b19ab6fcd1575d2fc52de777a8c4ead8c\user_sync-2.2.2-py3-none-any.whl\user_sync\connector\umapi.py", line 141, in iter_users
    for u in umapi_client.UsersQuery(self.connection):
  File "c:\pex\install\umapi_client-2.9-py2.py3-none-any.whl.9e8b5907a530f435b6b53572ac7f3f373a746472\umapi_client-2.9-py2.py3-none-any.whl\umapi_client\api.py", line 201, in __next__
    return self.next()
  File "c:\pex\install\umapi_client-2.9-py2.py3-none-any.whl.9e8b5907a530f435b6b53572ac7f3f373a746472\umapi_client-2.9-py2.py3-none-any.whl\umapi_client\api.py", line 197, in next
    return self.query._next_item()
  File "c:\pex\install\umapi_client-2.9-py2.py3-none-any.whl.9e8b5907a530f435b6b53572ac7f3f373a746472\umapi_client-2.9-py2.py3-none-any.whl\umapi_client\api.py", line 181, in _next_item
    self._next_page()
  File "c:\pex\install\umapi_client-2.9-py2.py3-none-any.whl.9e8b5907a530f435b6b53572ac7f3f373a746472\umapi_client-2.9-py2.py3-none-any.whl\umapi_client\api.py", line 172, in _next_page
    self.url_params, self.query_params)
  File "c:\pex\install\umapi_client-2.9-py2.py3-none-any.whl.9e8b5907a530f435b6b53572ac7f3f373a746472\umapi_client-2.9-py2.py3-none-any.whl\umapi_client\connection.py", line 249, in query_multiple
    raise re
  File "c:\pex\install\umapi_client-2.9-py2.py3-none-any.whl.9e8b5907a530f435b6b53572ac7f3f373a746472\umapi_client-2.9-py2.py3-none-any.whl\umapi_client\connection.py", line 241, in query_multiple
    result = self.make_call(query_path)
  File "c:\pex\install\umapi_client-2.9-py2.py3-none-any.whl.9e8b5907a530f435b6b53572ac7f3f373a746472\umapi_client-2.9-py2.py3-none-any.whl\umapi_client\connection.py", line 423, in make_call
    raise RequestError(result)
umapi_client.error.RequestError: Request Error (401): {"lastPage":false,"result":"error.internal.exceptionflys","message":"Failed to exchange token"}
2018-05-08 14:06:04 2960 INFO main - ========== End Run (User Sync version: 2.2.2) (Total time: 0:00:02)

**Comment by adobeDan** [comment]
This is a very strange error, and it typically means something went wrong on the Adobe server side.  It looks like, for some reason, the access token being used was not accepted by a back-end system.  The fact that it happened early in the run suggests that, _perhaps_, there is something wrong with your integration credential.  But that's a complete guess.  Is this a repeatable error?

**Comment by Tomomi99145** [comment]
this is a repeatable error.

**Comment by lsanesi** [comment]
Hi all - sorry to enter in this thread.
I have these issue too. Below the logs of last successful sync and first failed runs.
2018-04-30 16:00:03 7900 INFO main - ========== Start Run (User Sync version: 2.2.2) ============
2018-04-30 16:00:03 7900 INFO main - ------- Invocation parameters -------
2018-04-30 16:00:03 7900 INFO main - user-sync.pex --users mapped --process-groups
2018-04-30 16:00:03 7900 INFO main - -------------------------------------
2018-04-30 16:00:04 7900 INFO processor - ---------- Start Load from Directory -----------------------
2018-04-30 16:00:05 7900 INFO processor - ---------- End Load from Directory (Total time: 0:00:00) ---
2018-04-30 16:00:05 7900 INFO processor - ---------- Start Sync with UMAPI ---------------------------
2018-04-30 16:00:10 7900 INFO processor - ---------- End Sync with UMAPI (Total time: 0:00:05) -------
2018-04-30 16:00:10 7900 INFO processor - ---------------------------------- Action Summary ----------------------------------
2018-04-30 16:00:10 7900 INFO processor -                         Number of directory users read: 172
2018-04-30 16:00:10 7900 INFO processor -           Number of directory users selected for input: 172
2018-04-30 16:00:10 7900 INFO processor -                             Number of Adobe users read: 1163
2018-04-30 16:00:10 7900 INFO processor -            Number of Adobe users excluded from updates: 2
2018-04-30 16:00:10 7900 INFO processor -     Number of non-excluded Adobe users with no changes: 170
2018-04-30 16:00:10 7900 INFO processor -                        Number of new Adobe users added: 2
2018-04-30 16:00:10 7900 INFO processor -                 Number of matching Adobe users updated: 0
2018-04-30 16:00:10 7900 INFO processor -       Number of Adobe-only users with groups processed: 991
2018-04-30 16:00:10 7900 INFO processor -   Number of UMAPI actions sent (total, success, error): (2, 2, 0)
2018-04-30 16:00:10 7900 INFO processor - ------------------------------------------------------------------------------------
2018-04-30 16:00:10 7900 INFO main - ========== End Run (User Sync version: 2.2.2) (Total time: 0:00:07) 
2018-04-30 17:00:03 3484 INFO main - ========== Start Run (User Sync version: 2.2.2) ============
2018-04-30 17:00:03 3484 INFO main - ------- Invocation parameters -------
2018-04-30 17:00:03 3484 INFO main - user-sync.pex --users mapped --process-groups
2018-04-30 17:00:03 3484 INFO main - -------------------------------------
2018-04-30 17:00:05 3484 INFO processor - ---------- Start Load from Directory -----------------------
2018-04-30 17:00:05 3484 INFO processor - ---------- End Load from Directory (Total time: 0:00:00) ---
2018-04-30 17:00:05 3484 INFO processor - ---------- Start Sync with UMAPI ---------------------------
2018-04-30 17:00:05 3484 ERROR main - Unhandled exception
Traceback (most recent call last):
 File "c:\pex\install\user_sync-2.2.2-py2-none-any.whl.6647ef8e688d651fb2ca98c46f5ee85c0728df36\user_sync-2.2.2-py2-none-any.whl\user_sync\app.py", line 362, in main
   begin_work(config_loader)
 File "c:\pex\install\user_sync-2.2.2-py2-none-any.whl.6647ef8e688d651fb2ca98c46f5ee85c0728df36\user_sync-2.2.2-py2-none-any.whl\user_sync\app.py", line 213, in begin_work
   rule_processor.run(directory_groups, directory_connector, umapi_connectors)
 File "c:\pex\install\user_sync-2.2.2-py2-none-any.whl.6647ef8e688d651fb2ca98c46f5ee85c0728df36\user_sync-2.2.2-py2-none-any.whl\user_sync\rules.py", line 175, in run
   self.sync_umapi_users(umapi_connectors)
 File "c:\pex\install\user_sync-2.2.2-py2-none-any.whl.6647ef8e688d651fb2ca98c46f5ee85c0728df36\user_sync-2.2.2-py2-none-any.whl\user_sync\rules.py", line 426, in sync_umapi_users
   primary_adds_by_user_key = self.update_umapi_users_for_connector(umapi_info, umapi_connector)
 File "c:\pex\install\user_sync-2.2.2-py2-none-any.whl.6647ef8e688d651fb2ca98c46f5ee85c0728df36\user_sync-2.2.2-py2-none-any.whl\user_sync\rules.py", line 744, in update_umapi_users_for_connector
   for umapi_user in umapi_connector.iter_users():
 File "c:\pex\install\user_sync-2.2.2-py2-none-any.whl.6647ef8e688d651fb2ca98c46f5ee85c0728df36\user_sync-2.2.2-py2-none-any.whl\user_sync\connector\umapi.py", line 141, in iter_users
   for u in umapi_client.UsersQuery(self.connection):
 File "c:\pex\install\umapi_client-2.9-py2.py3-none-any.whl.9e8b5907a530f435b6b53572ac7f3f373a746472\umapi_client-2.9-py2.py3-none-any.whl\umapi_client\api.py", line 197, in next
   return self.query._next_item()
 File "c:\pex\install\umapi_client-2.9-py2.py3-none-any.whl.9e8b5907a530f435b6b53572ac7f3f373a746472\umapi_client-2.9-py2.py3-none-any.whl\umapi_client\api.py", line 181, in _next_item
   self._next_page()
 File "c:\pex\install\umapi_client-2.9-py2.py3-none-any.whl.9e8b5907a530f435b6b53572ac7f3f373a746472\umapi_client-2.9-py2.py3-none-any.whl\umapi_client\api.py", line 172, in _next_page
   self.url_params, self.query_params)
 File "c:\pex\install\umapi_client-2.9-py2.py3-none-any.whl.9e8b5907a530f435b6b53572ac7f3f373a746472\umapi_client-2.9-py2.py3-none-any.whl\umapi_client\connection.py", line 249, in query_multiple
   raise re
RequestError: Request Error (401): {"lastPage":false,"result":"error.internal.exceptionflys","message":"Failed to exchange token"}
2018-04-30 17:00:05 3484 INFO main - ========== End Run (User Sync version: 2.2.2) (Total time: 0:00:02)

The error is present also now.
Available to perform any test to get a solution.

**Comment by madumro** [comment]
Hi,
As a first step I would check if:
- the credentials filled in inside your _connector-umapi.yml_ file correspond to those from your integration,
- your public key is not expired.
Have you changed anything in your _connector-umapi.yml_ file recently?

**Comment by lsanesi** [comment]
Hi guys, we solved this issue recreating integration API using same public key.

**Comment by phil-levy** [comment]
I'm glad the problem is resolved.  Recreating the integration is something to try if your setup stops working for no apparent reason.
