### ISSUE TITLE
Problem decoding non ASCII characters when logging at debug level

### ISSUE THREAD

**Issue by tobiasbp** [adobe-apiplatform/user-sync.py#357]
When running in debug mode, I get errors when users have non ASCII characters in their names.

A users non ASCII last name: 'lastname': 'Kj\xe6rgaard'

The error as seen when logging at level debug

Arguments: ('before', {'email': 'foo@example.com', 'username': 'foo@example.com', 'domain': 'example.com', 'firstname': 'foo', 'lastname': 'Kj\xe6rgaard', 'country': None})
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 994, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe6' in position 196: ordinal not in range(128)
Call stack:
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "__main__.py", line 25, in <module>
    bootstrap_pex(__entry_point__)
  File ".bootstrap/_pex/pex_bootstrapper.py", line 170, in bootstrap_pex
    pex.PEX(entry_point).execute()
  File ".bootstrap/_pex/pex.py", line 365, in execute
    self._wrap_coverage(self._wrap_profiling, self._execute)
  File ".bootstrap/_pex/pex.py", line 293, in _wrap_coverage
    runner(*args)
  File ".bootstrap/_pex/pex.py", line 325, in _wrap_profiling
    runner(*args)
  File ".bootstrap/_pex/pex.py", line 408, in _execute
    return self.execute_entry(self._pex_info.entry_point)
  File ".bootstrap/_pex/pex.py", line 466, in execute_entry
    return runner(entry_point)
  File ".bootstrap/_pex/pex.py", line 471, in execute_module
    runpy.run_module(module_name, run_name='__main__')
  File "/usr/lib/python3.6/runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/.pex/install/user_sync-2.3rc4-py3-none-any.whl.1cf55a52d74f4ae2364c6225512f031f93f767bd/user_sync-2.3rc4-py3-none-any.whl/user_sync/app.py", line 325, in <module>
    main()
  File "/root/.pex/install/user_sync-2.3rc4-py3-none-any.whl.1cf55a52d74f4ae2364c6225512f031f93f767bd/user_sync-2.3rc4-py3-none-any.whl/user_sync/app.py", line 85, in main
    begin_work(config_loader)
  File "/root/.pex/install/user_sync-2.3rc4-py3-none-any.whl.1cf55a52d74f4ae2364c6225512f031f93f767bd/user_sync-2.3rc4-py3-none-any.whl/user_sync/app.py", line 321, in begin_work
    rule_processor.run(directory_groups, directory_connector, umapi_connectors)
  File "/root/.pex/install/user_sync-2.3rc4-py3-none-any.whl.1cf55a52d74f4ae2364c6225512f031f93f767bd/user_sync-2.3rc4-py3-none-any.whl/user_sync/rules.py", line 171, in run
    self.read_desired_user_groups(directory_groups, directory_connector)
  File "/root/.pex/install/user_sync-2.3rc4-py3-none-any.whl.1cf55a52d74f4ae2364c6225512f031f93f767bd/user_sync-2.3rc4-py3-none-any.whl/user_sync/rules.py", line 375, in read_desired_user_groups
    self.log_after_mapping_hook_scope(after_call=True)
  File "/root/.pex/install/user_sync-2.3rc4-py3-none-any.whl.1cf55a52d74f4ae2364c6225512f031f93f767bd/user_sync-2.3rc4-py3-none-any.whl/user_sync/rules.py", line 1037, in log_after_mapping_hook_scope
    self.logger.debug('Target attrs, %s: %s', when, self.after_mapping_hook_scope['target_attributes'])

**Comment by Luci2015** [comment]
You must be using an older release as I'm not getting any error using v. 2.3rc4

**Comment by tobiasbp** [comment]
Im using 2.3rc4 (As seen in the log I posted) in a docker image.

Maybe you users only have ASCII compliant names? Mine have danish characters (æøå).

**Comment by Luci2015** [comment]
Missed that! 
Well actually I used the exact name you pasted in the output: Kjærgaard.

No error in my case.
I think utf-8 is default for UST on this version, but can you check if around line 94 in connector-ldap.yml you have specified something else  for string-encoding?

**Comment by tobiasbp** [comment]
According to connector-ldap.yml, utf-8 is indeed the default. I had no setting for encoding, but tried to set the encoding like this:
string_encoding: utf8

I still get errors when logging at debug level.

Could I be missing something on the Python side? I'm running Ubuntu 16.04 with Python 3.6 from this ppa: deadsnakes/ppa

**Comment by Luci2015** [comment]
I don't have an ubuntu version to give you a confirmation - mine runs on unix.
Surely must be something related to writing to log file with special chars. Python3.6 also defaults to utf8, so I doubt is your version of Python.

**Comment by tobiasbp** [comment]
I have turned logging to file off (Level was info btw). The error still happens. I don't see how it could be related to writing log files.

**Comment by tobiasbp** [comment]
I just tried to log at level to debug file. I see none of the encoding related errors in the file. I only get those in the terminal.

**Comment by Luci2015** [comment]
i see. could be just writing to stdout then.
console log's handler also specifies:
`handler = logging.StreamHandler(sys.stdout)`

**Comment by tobiasbp** [comment]
So, it's a problem ión my side. Don't you agree?

**Comment by Luci2015** [comment]
I got hold of an Ubuntu machine - 16.04. This came with python 2.7.12 by default.
It also run just fine on this one too.
Can you download the sync tool for python2.7.12 version from the releases link and run the tool with python2.7 that came along with ubuntu?

**Comment by tobiasbp** [comment]
Which version of user-config would that be? It's not obvious to me (I have looked).

**Comment by Luci2015** [comment]
should be this one: user-sync-2.3rc4-ubuntu1604-py2712.tar.gz

**Comment by tobiasbp** [comment]
Doh! Hidden in plain sight ;)

I have updated my Docker image to use python 2.7 ('python' package in Ubuntu 16.04) . The error no longer appears.

**Comment by Luci2015** [comment]
great! thanks for confirming

**Comment by tobiasbp** [comment]
Should I close this?
