### ISSUE TITLE
The error "Failed to exchange token" again displayed.

### ISSUE THREAD

**Issue by Tomomi99145** [adobe-apiplatform/user-sync.py#367]
Error is displayed when executing user-sync command.
Please tell me the solution.

Example of execution
↓
2018-07-13 09:18:03 3644 INFO main - ========== Start Run (User Sync version: 2.2.2) ============
2018-07-13 09:18:03 3644 INFO main - ------- Invocation parameters -------
2018-07-13 09:18:03 3644 INFO main - user-sync.pex -t --users all --adobe-only-user-action exclude
2018-07-13 09:18:03 3644 DEBUG main - -------- Internal parameters --------
2018-07-13 09:18:03 3644 DEBUG main -   test_mode: True
2018-07-13 09:18:03 3644 DEBUG main -   config_filename: user-sync-config.yml
2018-07-13 09:18:03 3644 DEBUG main -   users: ['all']
2018-07-13 09:18:03 3644 DEBUG main -   username_filter_pattern: None
2018-07-13 09:18:03 3644 DEBUG main -   update_user_info: False
2018-07-13 09:18:03 3644 DEBUG main -   manage_groups: False
2018-07-13 09:18:03 3644 DEBUG main -   adobe_only_user_action: ['exclude']
2018-07-13 09:18:03 3644 DEBUG main -   stray_list_input_path: None
2018-07-13 09:18:03 3644 DEBUG main -   encoding_name: utf8
2018-07-13 09:18:03 3644 DEBUG main -   strategy: sync
2018-07-13 09:18:03 3644 INFO main - -------------------------------------
2018-07-13 09:18:03 3644 DEBUG ldap - ldap initialized with options: {'group_filter_format': '(&(|(objectCategory=group)(objectClass=groupOfNames)(objectClass=posixGroup))(cn={group}))', 'all_users_filter': '(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', 'group_member_filter_format': '(memberOf={group_dn})', 'require_tls_cert': False, 'string_encoding': 'utf8', 'user_identity_type_format': None, 'user_email_format': '{mail}', 'user_username_format': None, 'user_domain_format': None, 'user_identity_type': 'federatedID', 'search_page_size': 200, 'logger_name': 'ldap', 'host': 'ldaps://dooon.work', 'username': 'osabe@dooon.work', 'base_dn': 'DC=dooon,DC=work'}
2018-07-13 09:18:03 3644 DEBUG ldap - Connecting to: ldaps://dooon.work using username: osabe@dooon.work
2018-07-13 09:18:03 3644 DEBUG ldap - Connected
2018-07-13 09:18:03 3644 DEBUG umapi - UMAPI initialized with options: {'logger_name': 'umapi', 'test_mode': True, 'server': {'host': 'usermanagement.adobe.io', 'endpoint': '/v2/usermanagement', 'ims_host': 'ims-na1.adobelogin.com', 'ims_endpoint_jwt': '/ims/exchange/jwt', 'timeout': 120, 'retries': 3}, 'enterprise': {'org_id': '01830D295969307D0A495D1E@AdobeOrg', 'tech_acct': '622835905AF4E0320A495C04@techacct.adobe.com'}}
2018-07-13 09:18:03 3644 DEBUG umapi - umapi: reading private key data from file C:\user_sync\Utils\openSSL\private.key
2018-07-13 09:18:03 3644 DEBUG umapi - umapi: creating connection for org 01830D295969307D0A495D1E@AdobeOrg at endpoint https://usermanagement.adobe.io/v2/usermanagement
2018-07-13 09:18:04 3644 DEBUG urllib3.connectionpool - Starting new HTTPS connection (1): ims-na1.adobelogin.com
2018-07-13 09:18:05 3644 DEBUG urllib3.connectionpool - https://ims-na1.adobelogin.com:443 "POST /ims/exchange/jwt HTTP/1.1" 200 None
2018-07-13 09:18:05 3644 DEBUG umapi - umapi: connection established
2018-07-13 09:18:05 3644 DEBUG processor - Initialized with options: {'after_mapping_hook': None, 'default_country_code': 'JP', 'delete_strays': False, 'directory_group_filter': None, 'directory_group_mapped': False, 'disentitle_strays': False, 'exclude_groups': [], 'exclude_identity_types': ['adobeID'], 'exclude_strays': True, 'exclude_users': [], 'extended_attributes': None, 'manage_groups': False, 'max_adobe_only_users': 200, 'new_account_type': 'federatedID', 'remove_strays': False, 'strategy': 'sync', 'stray_list_input_path': None, 'stray_list_output_path': None, 'test_mode': True, 'update_user_info': False, 'username_filter_regex': None}
2018-07-13 09:18:05 3644 INFO processor - ---------- Start Load from Directory -----------------------
2018-07-13 09:18:05 3644 DEBUG processor - Building work list...
2018-07-13 09:18:05 3644 WARNING ldap - Skipping user with dn CN=dcaasadmin,CN=Users,DC=dooon,DC=work: empty email attribute (mail)
2018-07-13 09:18:05 3644 WARNING ldap - Skipping user with dn CN=Taro Adobe,OU=AADDC Users,DC=dooon,DC=work: empty email attribute (mail)
2018-07-13 09:18:05 3644 WARNING ldap - Skipping user with dn CN=Tomomi Osabe,OU=AADDC Users,DC=dooon,DC=work: empty email attribute (mail)
2018-07-13 09:18:05 3644 WARNING ldap - Skipping user with dn CN=osabe@adobe.com Osabe,OU=AADDC Users,DC=dooon,DC=work: empty email attribute (mail)
2018-07-13 09:18:05 3644 DEBUG ldap - Total users loaded: 0
2018-07-13 09:18:05 3644 DEBUG processor - Total directory users after filtering: 0
2018-07-13 09:18:05 3644 DEBUG processor - Group work list: {None: {}}
2018-07-13 09:18:05 3644 INFO processor - ---------- End Load from Directory (Total time: 0:00:00) ---
2018-07-13 09:18:05 3644 INFO processor - ---------- Start Sync with UMAPI ---------------------------
2018-07-13 09:18:05 3644 DEBUG processor - Syncing users to umapi...
2018-07-13 09:18:05 3644 DEBUG urllib3.connectionpool - Starting new HTTPS connection (1): usermanagement.adobe.io
2018-07-13 09:18:05 3644 DEBUG urllib3.connectionpool - https://usermanagement.adobe.io:443 "GET /v2/usermanagement/users/01830D295969307D0A495D1E@AdobeOrg/0?directOnly=True HTTP/1.1" 401 95
2018-07-13 09:18:05 3644 ERROR main - Unhandled exception
Traceback (most recent call last):
  File "c:\pex\install\user_sync-2.2.2-py3-none-any.whl.56859f7b19ab6fcd1575d2fc52de777a8c4ead8c\user_sync-2.2.2-py3-none-any.whl\user_sync\app.py", line 362, in main
    begin_work(config_loader)
  File "c:\pex\install\user_sync-2.2.2-py3-none-any.whl.56859f7b19ab6fcd1575d2fc52de777a8c4ead8c\user_sync-2.2.2-py3-none-any.whl\user_sync\app.py", line 213, in begin_work
    rule_processor.run(directory_groups, directory_connector, umapi_connectors)
  File "c:\pex\install\user_sync-2.2.2-py3-none-any.whl.56859f7b19ab6fcd1575d2fc52de777a8c4ead8c\user_sync-2.2.2-py3-none-any.whl\user_sync\rules.py", line 175, in run
    self.sync_umapi_users(umapi_connectors)
  File "c:\pex\install\user_sync-2.2.2-py3-none-any.whl.56859f7b19ab6fcd1575d2fc52de777a8c4ead8c\user_sync-2.2.2-py3-none-any.whl\user_sync\rules.py", line 426, in sync_umapi_users
    primary_adds_by_user_key = self.update_umapi_users_for_connector(umapi_info, umapi_connector)
  File "c:\pex\install\user_sync-2.2.2-py3-none-any.whl.56859f7b19ab6fcd1575d2fc52de777a8c4ead8c\user_sync-2.2.2-py3-none-any.whl\user_sync\rules.py", line 744, in update_umapi_users_for_connector
    for umapi_user in umapi_connector.iter_users():
  File "c:\pex\install\user_sync-2.2.2-py3-none-any.whl.56859f7b19ab6fcd1575d2fc52de777a8c4ead8c\user_sync-2.2.2-py3-none-any.whl\user_sync\connector\umapi.py", line 141, in iter_users
    for u in umapi_client.UsersQuery(self.connection):
  File "c:\pex\install\umapi_client-2.9-py2.py3-none-any.whl.9e8b5907a530f435b6b53572ac7f3f373a746472\umapi_client-2.9-py2.py3-none-any.whl\umapi_client\api.py", line 201, in __next__
    return self.next()
  File "c:\pex\install\umapi_client-2.9-py2.py3-none-any.whl.9e8b5907a530f435b6b53572ac7f3f373a746472\umapi_client-2.9-py2.py3-none-any.whl\umapi_client\api.py", line 197, in next
    return self.query._next_item()
  File "c:\pex\install\umapi_client-2.9-py2.py3-none-any.whl.9e8b5907a530f435b6b53572ac7f3f373a746472\umapi_client-2.9-py2.py3-none-any.whl\umapi_client\api.py", line 181, in _next_item
    self._next_page()
  File "c:\pex\install\umapi_client-2.9-py2.py3-none-any.whl.9e8b5907a530f435b6b53572ac7f3f373a746472\umapi_client-2.9-py2.py3-none-any.whl\umapi_client\api.py", line 172, in _next_page
    self.url_params, self.query_params)
  File "c:\pex\install\umapi_client-2.9-py2.py3-none-any.whl.9e8b5907a530f435b6b53572ac7f3f373a746472\umapi_client-2.9-py2.py3-none-any.whl\umapi_client\connection.py", line 249, in query_multiple
    raise re
  File "c:\pex\install\umapi_client-2.9-py2.py3-none-any.whl.9e8b5907a530f435b6b53572ac7f3f373a746472\umapi_client-2.9-py2.py3-none-any.whl\umapi_client\connection.py", line 241, in query_multiple
    result = self.make_call(query_path)
  File "c:\pex\install\umapi_client-2.9-py2.py3-none-any.whl.9e8b5907a530f435b6b53572ac7f3f373a746472\umapi_client-2.9-py2.py3-none-any.whl\umapi_client\connection.py", line 423, in make_call
    raise RequestError(result)
umapi_client.error.RequestError: Request Error (401): {"lastPage":false,"result":"error.internal.exceptionflys","message":"Failed to exchange token"}
2018-07-13 09:18:05 3644 INFO main - ========== End Run (User Sync version: 2.2.2) (Total time: 0:00:01)

**Comment by janssenda-adobe** [comment]
Interesting - does it fail at the same point (right after starting umapi sync) every time, or does the token exchange fail on other connection points as well?

**Comment by janssenda-adobe** [comment]
@adobeDan per the conversation we had via email on this

**Comment by Tomomi99145** [comment]
yes,it fail at the same point (right after starting umapi sync) every time.

**Comment by janssenda-adobe** [comment]
It's got to be a UMAPI internal issue.  I still can't reproduce the exception even when I directly modify my connection data in the umapi client at the same point in the code.

**Comment by Lalofuin** [comment]
I have the sam Probleme since 2018-07-08.

Any Solutions ?

2018-07-18 16:28:59 5892 INFO processor - ---------- Start Sync with UMAPI ---------------------------
2018-07-18 16:28:59 5892 DEBUG processor - Syncing users to umapi...
2018-07-18 16:28:59 5892 DEBUG urllib3.connectionpool - Starting new HTTPS connection (1): usermanagement.adobe.io
2018-07-18 16:28:59 5892 DEBUG urllib3.connectionpool - https://usermanagement.adobe.io:443 "GET /v2/usermanagement/users/xxxxxxxxxxxxxxxxxxxxxxxxxxxx@AdobeOrg/0?directOnly=True HTTP/1.1" 401 95
2018-07-18 16:28:59 5892 ERROR main - Unhandled exception
Traceback (most recent call last):
  File "c:\pex\install\user_sync-2.3rc4-py3-none-any.whl.b543203119784d7dd2b01995d2e5b70404d06e98\user_sync-2.3rc4-py3-none-any.whl\user_sync\app.py", line 85,
in main
    begin_work(config_loader)
  File "c:\pex\install\user_sync-2.3rc4-py3-none-any.whl.b543203119784d7dd2b01995d2e5b70404d06e98\user_sync-2.3rc4-py3-none-any.whl\user_sync\app.py", line 321,
 in begin_work
    rule_processor.run(directory_groups, directory_connector, umapi_connectors)
  File "c:\pex\install\user_sync-2.3rc4-py3-none-any.whl.b543203119784d7dd2b01995d2e5b70404d06e98\user_sync-2.3rc4-py3-none-any.whl\user_sync\rules.py", line 17
7, in run
    self.sync_umapi_users(umapi_connectors)
  File "c:\pex\install\user_sync-2.3rc4-py3-none-any.whl.b543203119784d7dd2b01995d2e5b70404d06e98\user_sync-2.3rc4-py3-none-any.whl\user_sync\rules.py", line 42
8, in sync_umapi_users
    primary_adds_by_user_key = self.update_umapi_users_for_connector(umapi_info, umapi_connector)
  File "c:\pex\install\user_sync-2.3rc4-py3-none-any.whl.b543203119784d7dd2b01995d2e5b70404d06e98\user_sync-2.3rc4-py3-none-any.whl\user_sync\rules.py", line 74
8, in update_umapi_users_for_connector
    for umapi_user in umapi_connector.iter_users():
  File "c:\pex\install\user_sync-2.3rc4-py3-none-any.whl.b543203119784d7dd2b01995d2e5b70404d06e98\user_sync-2.3rc4-py3-none-any.whl\user_sync\connector\umapi.py
", line 141, in iter_users
    for u in umapi_client.UsersQuery(self.connection):
  File "c:\pex\install\umapi_client-2.10-py2.py3-none-any.whl.34defdf0b0f75cd67b5b802479135cd44930a6d5\umapi_client-2.10-py2.py3-none-any.whl\umapi_client\api.p
y", line 201, in __next__
    return self.next()
  File "c:\pex\install\umapi_client-2.10-py2.py3-none-any.whl.34defdf0b0f75cd67b5b802479135cd44930a6d5\umapi_client-2.10-py2.py3-none-any.whl\umapi_client\api.p
y", line 197, in next
    return self.query._next_item()
  File "c:\pex\install\umapi_client-2.10-py2.py3-none-any.whl.34defdf0b0f75cd67b5b802479135cd44930a6d5\umapi_client-2.10-py2.py3-none-any.whl\umapi_client\api.p
y", line 181, in _next_item
    self._next_page()
  File "c:\pex\install\umapi_client-2.10-py2.py3-none-any.whl.34defdf0b0f75cd67b5b802479135cd44930a6d5\umapi_client-2.10-py2.py3-none-any.whl\umapi_client\api.p
y", line 172, in _next_page
    self.url_params, self.query_params)
  File "c:\pex\install\umapi_client-2.10-py2.py3-none-any.whl.34defdf0b0f75cd67b5b802479135cd44930a6d5\umapi_client-2.10-py2.py3-none-any.whl\umapi_client\conne
ction.py", line 266, in query_multiple
    raise re
  File "c:\pex\install\umapi_client-2.10-py2.py3-none-any.whl.34defdf0b0f75cd67b5b802479135cd44930a6d5\umapi_client-2.10-py2.py3-none-any.whl\umapi_client\conne
ction.py", line 258, in query_multiple
    result = self.make_call(query_path)
  File "c:\pex\install\umapi_client-2.10-py2.py3-none-any.whl.34defdf0b0f75cd67b5b802479135cd44930a6d5\umapi_client-2.10-py2.py3-none-any.whl\umapi_client\conne
ction.py", line 440, in make_call
    raise RequestError(result)
umapi_client.error.RequestError: Request Error (401): {"lastPage":false,"result":"error.internal.exceptionflys","message":"Failed to exchange token"}
2018-07-18 16:28:59 5892 INFO main - ========== End Run (User Sync version: 2.3rc4) (Total time: 0:00:01)
