### ISSUE TITLE
Unhandled Exception Error

### ISSUE THREAD

**Issue by CompdudeWes** [adobe-apiplatform/user-sync.py#406]
Ran into this error,  Not sure where to start on this one.

2018-09-21 16:20:39 4912 INFO main - ========== End Run (User Sync version: 2.3) (Total time: 0:00:00) 
2018-09-21 16:23:15 5092 INFO main - ========== Start Run (User Sync version: 2.3) ==============
2018-09-21 16:23:15 5092 INFO main - Python version: 3.6.5 on win32
2018-09-21 16:23:15 5092 INFO main - ------- Command line arguments -------
2018-09-21 16:23:15 5092 INFO main - --process-groups --users mapped -t
2018-09-21 16:23:15 5092 INFO main - -------------------------------------
2018-09-21 16:23:16 5092 INFO processor - ---------- Start Load from Directory -----------------------
2018-09-21 16:23:16 5092 ERROR main - Unhandled exception
Traceback (most recent call last):
  File "c:\pex\install\user_sync-2.3-py3-none-any.whl.0d3165175054f7d7ed22c445092a54076a10dafa\user_sync-2.3-py3-none-any.whl\user_sync\app.py", line 85, in main
    begin_work(config_loader)
  File "c:\pex\install\user_sync-2.3-py3-none-any.whl.0d3165175054f7d7ed22c445092a54076a10dafa\user_sync-2.3-py3-none-any.whl\user_sync\app.py", line 322, in begin_work
    rule_processor.run(directory_groups, directory_connector, umapi_connectors)
  File "c:\pex\install\user_sync-2.3-py3-none-any.whl.0d3165175054f7d7ed22c445092a54076a10dafa\user_sync-2.3-py3-none-any.whl\user_sync\rules.py", line 171, in run
    self.read_desired_user_groups(directory_groups, directory_connector)
  File "c:\pex\install\user_sync-2.3-py3-none-any.whl.0d3165175054f7d7ed22c445092a54076a10dafa\user_sync-2.3-py3-none-any.whl\user_sync\rules.py", line 332, in read_desired_user_groups
    all_users=directory_group_filter is None)
  File "c:\pex\install\user_sync-2.3-py3-none-any.whl.0d3165175054f7d7ed22c445092a54076a10dafa\user_sync-2.3-py3-none-any.whl\user_sync\connector\directory.py", line 60, in load_users_and_groups
    all_users=all_users)
  File "c:\pex\install\user_sync-2.3-py3-none-any.whl.0d3165175054f7d7ed22c445092a54076a10dafa\user_sync-2.3-py3-none-any.whl\user_sync\connector\directory_ldap.py", line 56, in connector_load_users_and_groups
    return state.load_users_and_groups(groups or [], extended_attributes or [], all_users)
  File "c:\pex\install\user_sync-2.3-py3-none-any.whl.0d3165175054f7d7ed22c445092a54076a10dafa\user_sync-2.3-py3-none-any.whl\user_sync\connector\directory_ldap.py", line 142, in load_users_and_groups
    group_member_subfilter = self.format_ldap_query_string(group_member_filter_format, group_dn=group_dn)
  File "c:\pex\install\user_sync-2.3-py3-none-any.whl.0d3165175054f7d7ed22c445092a54076a10dafa\user_sync-2.3-py3-none-any.whl\user_sync\connector\directory_ldap.py", line 378, in format_ldap_query_string
    return query.format(**escaped_args)
KeyError: 'Users'
2018-09-21 16:23:16 5092 INFO main - ========== End Run (User Sync version: 2.3) (Total time: 0:00:00)

**Comment by janssenda-adobe** [comment]
Could you post the connector-ldap.yml and user-sync-config.yml?

**Comment by CompdudeWes** [comment]
Here is the file.  Thank you for the help!
[connector-ldap.zip](https://github.com/adobe-apiplatform/user-sync.py/files/2410996/connector-ldap.zip)

**Comment by Luci2015** [comment]
In fact, your connector ldap file says
_group_member_filter_format: "(memberOf={Users})"_
You should try this:
_group_member_filter_format: "(memberOf:1.2.840.113556.1.4.1941:={group_dn})"_

**Comment by adorton-adobe** [comment]
@bajwa-adobe win32 in this case is just the way Python reports the platform.  It doesn't necessarily mean that the Python build is win32.  If it was, the sync tool would fail to find several dependencies.

@CompdudeWes - @Luci2015 is correct - you need to specify `group_dn` in the curly braces.  If you're querying Active Directory, you probably don't need to customize the group membership query.  

The default for AD is

`group_member_filter_format: "(memberOf={group_dn})"`

If you want to enable nested group support, you can enable this option

`group_member_filter_format: "(memberOf:1.2.840.113556.1.4.1941:={group_dn})"`

If you don't need nesting I recommend using the default non-nested query, as the nesting condition will make your LDAP queries a lot slower.

**Comment by CompdudeWes** [comment]
That fixed it!  thank you for your help!
