### ISSUE TITLE
Unhandled exception when slight error in config file

### ISSUE THREAD

**Issue by phil-levy** [adobe-apiplatform/user-sync.py#49]
If you have
limits:
    max_deletions_per_run= 10    

you get
2017-03-02 17:31:55 17952 ERROR main - Unhandled exception
Traceback (most recent call last):
  File "c:\user-sync\.pex\install\user_sync-1.1.1-py2-none-any.whl.1d38cd7281dcf25d7c48135e8d87ce573a9f8c9f\user_sync-1.1.1-py2-none-any.whl\user_sync\app.py", line 256, in main
    config_loader = create_config_loader(args)
  File "c:\user-sync\.pex\install\user_sync-1.1.1-py2-none-any.whl.1d38cd7281dcf25d7c48135e8d87ce573a9f8c9f\user_sync-1.1.1-py2-none-any.whl\user_sync\app.py", line 184, in create_config_loader
    config_loader = user_sync.config.ConfigLoader(config_bootstrap_options)
  File "c:\user-sync\.pex\install\user_sync-1.1.1-py2-none-any.whl.1d38cd7281dcf25d7c48135e8d87ce573a9f8c9f\user_sync-1.1.1-py2-none-any.whl\user_sync\config.py", line 75, in __init__
    config_content = self.load_from_yaml(self.main_config_path)
  File "c:\user-sync\.pex\install\user_sync-1.1.1-py2-none-any.whl.1d38cd7281dcf25d7c48135e8d87ce573a9f8c9f\user_sync-1.1.1-py2-none-any.whl\user_sync\config.py", line 260, in load_from_yaml
    return yaml.load(input_file)
  File "c:\user-sync\.pex\install\pyyaml-3.12-cp27-cp27m-win_amd64.whl.95f7f7154d83db289311a6943ed874bc14dae938\pyyaml-3.12-cp27-cp27m-win_amd64.whl\yaml\__init__.py", line 71, in load
    return loader.get_single_data()
  File "c:\user-sync\.pex\install\pyyaml-3.12-cp27-cp27m-win_amd64.whl.95f7f7154d83db289311a6943ed874bc14dae938\pyyaml-3.12-cp27-cp27m-win_amd64.whl\yaml\constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "c:\user-sync\.pex\install\pyyaml-3.12-cp27-cp27m-win_amd64.whl.95f7f7154d83db289311a6943ed874bc14dae938\pyyaml-3.12-cp27-cp27m-win_amd64.whl\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "c:\user-sync\.pex\install\pyyaml-3.12-cp27-cp27m-win_amd64.whl.95f7f7154d83db289311a6943ed874bc14dae938\pyyaml-3.12-cp27-cp27m-win_amd64.whl\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "c:\user-sync\.pex\install\pyyaml-3.12-cp27-cp27m-win_amd64.whl.95f7f7154d83db289311a6943ed874bc14dae938\pyyaml-3.12-cp27-cp27m-win_amd64.whl\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "c:\user-sync\.pex\install\pyyaml-3.12-cp27-cp27m-win_amd64.whl.95f7f7154d83db289311a6943ed874bc14dae938\pyyaml-3.12-cp27-cp27m-win_amd64.whl\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "c:\user-sync\.pex\install\pyyaml-3.12-cp27-cp27m-win_amd64.whl.95f7f7154d83db289311a6943ed874bc14dae938\pyyaml-3.12-cp27-cp27m-win_amd64.whl\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "c:\user-sync\.pex\install\pyyaml-3.12-cp27-cp27m-win_amd64.whl.95f7f7154d83db289311a6943ed874bc14dae938\pyyaml-3.12-cp27-cp27m-win_amd64.whl\yaml\parser.py", line 439, in parse_block_mapping_key
    "expected <block end>, but found %r" % token.id, token.start_mark)
ParserError: while parsing a block mapping
  in "user-sync-config.yml", line 1, column 1
expected <block end>, but found '<block mapping start>'
  in "user-sync-config.yml", line 81, column 5

Sometimes there is a perfectly good error message at the end of stack trace though not in this case.

We should get as good a message as possible with the file/line/column if known and not unhandled exception.

**Comment by adobeDan** [comment]
Phil, I'm not sure what you're expecting here.  The YAML parser is failing, and giving the exact error message: expected a space, got no space.  It's just formatted without the quotes.  Are you complaining about the traceback in front of the error message?  Then we should catch the YAML parsing error, log it, and quit cleanly.  That seems like a reasonable enhancement request.

**Comment by phil-levy** [comment]
Yes, that would be good.  The giant stack trace is not a good first experience since this is a likely error for a new user to make.

**Comment by adobeDan** [comment]
@ianmak Next time please reference the issue in your commit message, using the form "Fixes #49" (or whatever the number is), because that way when your commit gets merged the issue will auto-close.
