### ISSUE TITLE
Running user-sync.pex always returns these values. Not sure what the issue is

### ISSUE THREAD

**Issue by astrugatch** [adobe-apiplatform/user-sync.py#500]
Traceback (most recent call last):
  File "C:\Users\AdobeSyncAdmin\user_sync_tool\user-sync.pex\.bootstrap\_pex\pex.py", line 347, in execute
  File "C:\Users\AdobeSyncAdmin\user_sync_tool\user-sync.pex\.bootstrap\_pex\pex.py", line 90, in _activate
  File "C:\Users\AdobeSyncAdmin\user_sync_tool\user-sync.pex\.bootstrap\_pex\environment.py", line 163, in activate
  File "C:\Users\AdobeSyncAdmin\user_sync_tool\user-sync.pex\.bootstrap\_pex\environment.py", line 217, in _activate
  File "C:\Users\AdobeSyncAdmin\user_sync_tool\user-sync.pex\.bootstrap\_pex\environment.py", line 152, in update_candidate_distributions
  File "C:\Users\AdobeSyncAdmin\user_sync_tool\user-sync.pex\.bootstrap\_pex\environment.py", line 122, in load_internal_cache
  File "C:\Users\AdobeSyncAdmin\user_sync_tool\user-sync.pex\.bootstrap\_pex\environment.py", line 109, in write_zipped_internal_cache
  File "C:\Users\AdobeSyncAdmin\user_sync_tool\user-sync.pex\.bootstrap\_pex\util.py", line 178, in cache_distribution
  File "C:\Users\AdobeSyncAdmin\user_sync_tool\user-sync.pex\.bootstrap\_pex\common.py", line 141, in safe_open
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\AdobeSyncAdmin\\.pex\\install\\pycryptodome-3.7.3-cp27-cp27m-win_amd64.whl.15d9925784d1c511e92c1fa1c4a2769414a4fcac.9ebb499e99a6435e8b976a670c48abc6\\pycryptodome-3.7.3-cp27-cp27m-win_amd64.whl\\Crypto/SelfTest/Cipher/test_vectors/AES/gcmEncryptExtIV128.rsp'

**Comment by astrugatch** [comment]
Just read the success guide (had been following the guide here: https://helpx.adobe.com/enterprise/using/user-sync.html) and see the max path length setting. I will see if this resolves my issue

**Comment by astrugatch** [comment]
Well now I have a different issue. I get:

```
Failed to execute PEX file, missing win_amd64-cp-36-cp36m compatible dependencies for:
cffi
enum34
psutil
pyyaml
umapi-client
user-sync
cryptography
pycryptodome
click-default-group
```
after running 
`python user-sync.pex --version`

**Comment by vossen-adobe** [comment]
are you on 32 bit platform or python 3.7?

**Comment by astrugatch** [comment]
No. Windows 10 LTSC x64 and python 3.6

**Comment by vossen-adobe** [comment]
I think you may have downloaded the 2.7 pex file?
