### ISSUE TITLE
Encoding Issue Sync Tool

### ISSUE THREAD

**Issue by rogeian** [adobe-apiplatform/user-sync.py#502]
When we're trying to run the sync tool we're getting the following error, we've tried in the file connector-ldap.yml with string_encoding: 'latin1' & string_encoding: 'utf8' using Windows Server 2016

---------- 

:\Users\ldapadobesync\user_sync_tool>python user-sync.pex -t
2019-06-20 15:36:11 1120 INFO config - Using main config file: user-sync-config.yml (encoding utf8)
2019-06-20 15:36:12 1120 INFO main - ========== Start Run (User Sync version: 2.5.0) ============
2019-06-20 15:36:12 1120 INFO main - Python version: 3.6.8 on win32
2019-06-20 15:36:12 1120 INFO main - ------- Command line arguments -------
2019-06-20 15:36:12 1120 INFO main - -t
2019-06-20 15:36:12 1120 INFO main - -------------------------------------
2019-06-20 15:36:13 1120 ERROR main - Unhandled exception
Traceback (most recent call last):
  File "c:\users\ldapadobesync\.pex\install\user_sync-2.5.0-py3-none-any.whl.ca0d28cf9aff9cbdf629d97080d9bbb8a649f3bf\user_sync-2.5.0-py3-none-any.whl\user_sync\app.py", line 173, in sync
    begin_work(config_loader)
  File "c:\users\ldapadobesync\.pex\install\user_sync-2.5.0-py3-none-any.whl.ca0d28cf9aff9cbdf629d97080d9bbb8a649f3bf\user_sync-2.5.0-py3-none-any.whl\user_sync\app.py", line 340, in begin_work
    umapi_primary_connector = user_sync.connector.umapi.UmapiConnector(primary_name, primary_umapi_config)
  File "c:\users\ldapadobesync\.pex\install\user_sync-2.5.0-py3-none-any.whl.ca0d28cf9aff9cbdf629d97080d9bbb8a649f3bf\user_sync-2.5.0-py3-none-any.whl\user_sync\connector\umapi.py", line 96, in __init__
    key_data = f.read()
  File "C:\Users\ldapadobesync\AppData\Local\Programs\Python\Python36\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 207: character maps to <undefined>
2019-06-20 15:36:13 1120 INFO main - ========== End Run (User Sync version: 2.5.0) (Total time: 0:00:01)

**Comment by cosmin-balanoiu** [comment]
This was sorted via a web session. The culprit was a faulty private key: invalid format and encoding.
