### ISSUE TITLE
Error undefined symbol "PyUnicodeUCS2_FromUnicode" on EL7 64-bit

### ISSUE THREAD

**Issue by prynhart** [adobe-apiplatform/user-sync.py#55]
I've copied the example files, and just edited dashboard-config.yml & user-sync-config.yml (to try and get something minimal working) - but I'm seeing an Unhandled Exception from the user-sync tool, and not sure how to proceed.

Here are my edits to the two yml files (actual values removed and replaced with X's):

```
$ diff dashboard-config.yml.ORIG dashboard-config.yml
9,13c9,13
<   org_id: "Org ID goes here"
<   api_key: "API key goes here"
<   client_secret: "Client secret goes here"
<   tech_acct: "Tech account ID goes here"
<   priv_key_path: "Path to private.key goes here"
---
>   org_id: "96AEE1CE543800880A4C98A5@AdobeOrg"
>   api_key: "XXXXXXXXXXXXXXXXXXXXXX"
>   client_secret: "XXXXXXX-XXXXX-XXXXX-XXXXX-XXXXXXXX"
>   tech_acct: "XXXXXXXXXXXX@techacct.adobe.com"
>   priv_key_path: "/home/p/prynhart/private.key"

$ diff user-sync-config.yml.ORIG user-sync-config.yml
12c12
<   # owning: example.dashboard-config.yml
>   owning: dashboard-config.yml
<   # user_identity_type: enterpriseID
>   user_identity_type: federatedID
>   console_log_level: debug
```

I thought that this would be enough to establish a secure connection - not sure what to make of the crash.  The actual traceback that I'm getting is pasted inline below.  Any hints would be appreciated.

Thanks,

Patrick

```
$ ./user-sync
2017-03-09 10:20:59 30841 INFO config - Using main config file: user-sync-config.yml
2017-03-09 10:20:59 30841 INFO main - ========== Start Run =======================================
2017-03-09 10:20:59 30841 INFO dashboard.owning - Creating connection for org id: "96AEE1CE543800880A4C98A5@AdobeOrg" using private key file: "/home/p/prynhart/private.key"
2017-03-09 10:20:59 30841 ERROR main - Unhandled exception
Traceback (most recent call last):
  File "/home/p/prynhart/.pex/install/user_sync-1.1.1-py2-none-any.whl.21a3a678dccecc3c248aaab94e34af462a77008d/user_sync-1.1.1-py2-none-any.whl/user_sync/app.py", line 270, in main
    begin_work(config_loader)
  File "/home/p/prynhart/.pex/install/user_sync-1.1.1-py2-none-any.whl.21a3a678dccecc3c248aaab94e34af462a77008d/user_sync-1.1.1-py2-none-any.whl/user_sync/app.py", line 166, in begin_work
    dashboard_owning_connector = user_sync.connector.dashboard.DashboardConnector("owning", owning_dashboard_config)
  File "/home/p/prynhart/.pex/install/user_sync-1.1.1-py2-none-any.whl.21a3a678dccecc3c248aaab94e34af462a77008d/user_sync-1.1.1-py2-none-any.whl/user_sync/connector/dashboard.py", line 93, in __init__
    user_agent="user-sync/" + APP_VERSION
  File "/home/p/prynhart/.pex/install/umapi_client-2.0.3-py2.py3-none-any.whl.27fb02ed364b2eb12931a3425c557b9f3d7fbe82/umapi_client-2.0.3-py2.py3-none-any.whl/umapi_client/connection.py", line 114, in __init__
    self.auth = self._get_auth(ims_host=ims_host, ims_endpoint_jwt=ims_endpoint_jwt, **auth_dict)
  File "/home/p/prynhart/.pex/install/umapi_client-2.0.3-py2.py3-none-any.whl.27fb02ed364b2eb12931a3425c557b9f3d7fbe82/umapi_client-2.0.3-py2.py3-none-any.whl/umapi_client/connection.py", line 130, in _get_auth
    token = AccessRequest("https://" + ims_host + ims_endpoint_jwt, api_key, client_secret, jwt())
  File "/home/p/prynhart/.pex/install/umapi_client-2.0.3-py2.py3-none-any.whl.27fb02ed364b2eb12931a3425c557b9f3d7fbe82/umapi_client-2.0.3-py2.py3-none-any.whl/umapi_client/auth.py", line 51, in __call__
    jwt_token = jwt.encode(payload, self.key, algorithm='RS256')
  File "/home/p/prynhart/.pex/install/PyJWT-1.4.2-py2.py3-none-any.whl.e2814ae802fc1ffaca54777c9702d5c27e3f22ee/PyJWT-1.4.2-py2.py3-none-any.whl/jwt/api_jwt.py", line 56, in encode
    json_payload, key, algorithm, headers, json_encoder
  File "/home/p/prynhart/.pex/install/PyJWT-1.4.2-py2.py3-none-any.whl.e2814ae802fc1ffaca54777c9702d5c27e3f22ee/PyJWT-1.4.2-py2.py3-none-any.whl/jwt/api_jws.py", line 98, in encode
    key = alg_obj.prepare_key(key)
  File "/home/p/prynhart/.pex/install/PyJWT-1.4.2-py2.py3-none-any.whl.e2814ae802fc1ffaca54777c9702d5c27e3f22ee/PyJWT-1.4.2-py2.py3-none-any.whl/jwt/algorithms.py", line 167, in prepare_key
    key = load_pem_private_key(key, password=None, backend=default_backend())
  File "/home/p/prynhart/.pex/install/cryptography-1.7.2-cp27-cp27m-linux_x86_64.whl.97c7929f138bb30736fdb7bae240a1582722a8f2/cryptography-1.7.2-cp27-cp27m-linux_x86_64.whl/cryptography/hazmat/backends/__init__.py", line 71, in default_backend
    _default_backend = MultiBackend(_available_backends())
  File "/home/p/prynhart/.pex/install/cryptography-1.7.2-cp27-cp27m-linux_x86_64.whl.97c7929f138bb30736fdb7bae240a1582722a8f2/cryptography-1.7.2-cp27-cp27m-linux_x86_64.whl/cryptography/hazmat/backends/__init__.py", line 28, in _available_backends
    "cryptography.backends"
  File "/home/p/prynhart/user-sync/.bootstrap/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/p/prynhart/.pex/install/cryptography-1.7.2-cp27-cp27m-linux_x86_64.whl.97c7929f138bb30736fdb7bae240a1582722a8f2/cryptography-1.7.2-cp27-cp27m-linux_x86_64.whl/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/home/p/prynhart/.pex/install/cryptography-1.7.2-cp27-cp27m-linux_x86_64.whl.97c7929f138bb30736fdb7bae240a1582722a8f2/cryptography-1.7.2-cp27-cp27m-linux_x86_64.whl/cryptography/hazmat/backends/openssl/backend.py", line 17, in <module>
    from cryptography import utils, x509
  File "/home/p/prynhart/.pex/install/cryptography-1.7.2-cp27-cp27m-linux_x86_64.whl.97c7929f138bb30736fdb7bae240a1582722a8f2/cryptography-1.7.2-cp27-cp27m-linux_x86_64.whl/cryptography/x509/__init__.py", line 7, in <module>
    from cryptography.x509.base import (
  File "/home/p/prynhart/.pex/install/cryptography-1.7.2-cp27-cp27m-linux_x86_64.whl.97c7929f138bb30736fdb7bae240a1582722a8f2/cryptography-1.7.2-cp27-cp27m-linux_x86_64.whl/cryptography/x509/base.py", line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "/home/p/prynhart/.pex/install/cryptography-1.7.2-cp27-cp27m-linux_x86_64.whl.97c7929f138bb30736fdb7bae240a1582722a8f2/cryptography-1.7.2-cp27-cp27m-linux_x86_64.whl/cryptography/x509/extensions.py", line 20, in <module>
    from cryptography.hazmat.primitives import constant_time, serialization
  File "/home/p/prynhart/.pex/install/cryptography-1.7.2-cp27-cp27m-linux_x86_64.whl.97c7929f138bb30736fdb7bae240a1582722a8f2/cryptography-1.7.2-cp27-cp27m-linux_x86_64.whl/cryptography/hazmat/primitives/constant_time.py", line 9, in <module>
    from cryptography.hazmat.bindings._constant_time import lib
ImportError: /home/p/prynhart/.pex/install/cffi-1.9.1-cp27-cp27m-linux_x86_64.whl.9f1fc2a07650a8df3e6ebc7cd4f5dd4d7a6eb9d9/cffi-1.9.1-cp27-cp27m-linux_x86_64.whl/_cffi_backend.so: undefined symbol: PyUnicodeUCS2_FromUnicode
2017-03-09 10:20:59 30841 INFO main - ========== End Run (Total time: 0:00:00) ===================
```

**Comment by prynhart** [comment]
Okay - I see this is due to the error undefined symbol "PyUnicodeUCS2_FromUnicode".  We are on CentOS EL7 64-bit, not sure what we're missing for the PEX to fail like this ?

Thanks,

Patrick

**Comment by bhunut-adobe** [comment]
@prynhart I had the same issue with ubuntu 1.1.1 release. I ended up downloading the code and build it under my environment.

Here is my quick note on how to build from the src under CentOS 7 .

```
CentOS 7 Build Pre Req:

yum install epel-release gcc python-devel openssl-devel openldap-devel

pip install –upgrade pip
pip install virtualenv

==================================================

Python 2.7.13 Alternative Install

https://tecadmin.net/install-python-2-7-on-centos-rhel/#

Run: 

./configure

after running ./configure

Open Modules/Setup file and search for zlib.

Uncommented this line “zlib zlibmodule.c –I$(prefix)/include –L$(exec_prefix)/lib –lz”

Save and exit

Run: 

make altinstall

==================================================

Make virual environment with python 2.7.13

virtualenv –p /usr/local/bin/python2.7 py2713_user_sync_env

Activate virtualEnv

source py2713_user_sync_env/bin/activate


Go to the source and Build by running this command: make pex
```

**Comment by prynhart** [comment]
@bhunut-adobe: Thank you very much - I will need to try those build instructions.

To the Adobe User-Sync.py team, do you think it would be possible to have an EL7 build provided.  In our organisation, we are only running EL7 on Servers (i.e. can't deploy Ubuntu due to policy).  If an EL7 PEX build is not something that can be provided, can there be come official build instructions  for this OS ?

With Thanks

Patrick

**Comment by prynhart** [comment]
Or maybe there is some way that a 'universal' Linux build could be made (i.e. one that supports both Ubuntu & EL7) ?

**Comment by prynhart** [comment]
Just wanted to confirm that I'm seeing this when using the CentOS build provided `user-sync-centos-v1.1.1.tar.gz` when running under EL7 and using python-2.7.5-48.el7.x86_64

**Comment by chesterl86** [comment]
This may be a result of a difference in unicode that was set when compiling python 2.7.13. Will re-compile python using a different unicode to see if I can reproduce what you are seeing.

**Comment by chesterl86** [comment]
Python installations seems to default to using unicode ucs2. After re-configuring and re-compiling python 2.7.13 using `--enable-unicode=ucs4` and running 1.1.1, I am able to reproduce the issue being reported by Patrick when running the tool.

@prynhart Out of curiosity, would you mind doing a quick test and run `python -c 'import sys; print sys.maxunicode'`. Im interested to see what the output for you would be.

**Comment by prynhart** [comment]
Sure thing - and thank you for investigating :-)
 
Firstly, just to confirm this is an EL7 box using the default (vendor shipped RPMs):
```
# uname -a
Linux tur-ds-subsdev1.massey.ac.nz 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
# whereis python
python: /usr/bin/python2.7 /usr/bin/python /usr/bin/python2.7-config /usr/lib/python2.7 /usr/lib64/python2.7 /etc/python /usr/include/python2.7 /usr/share/man/man1/python.1.gz
# yum provides '*/python2.7'

<snip>
python-2.7.5-34.el7.x86_64 : An interpreted, interactive, object-oriented programming language
Repo        : Default_Organization_Centos7_os_x86_64
Matched from:
Filename    : /usr/bin/python2.7
</snip>
```

And for the command you've requested:
```
# python -c 'import sys; print sys.maxunicode'
1114111
```

**Comment by adobeDan** [comment]
Resolved: We will be building all future releases of User Sync with the platform-native python (i.e, the one that ships with the platform) where there is one.  On Windows we will use the standard python.org build of the latest 2.7 release, and where we use custom builds of extensions on Windows we will post them in the sources so people can build their own.
