### ISSUE TITLE
post-sync sign connector issue

### ISSUE THREAD

**Issue by Luci2015** [adobe-apiplatform/user-sync.py#636]
**Description**
UST returns an error after many queries run against Sign api endpoint.
This issue is not reproducing every time, but most of the time since middle of August.

here is the traceback:
```
2020-09-17 08:41:36 2108 ERROR main - Unhandled exception
Traceback (most recent call last):
  File "lib\site-packages\urllib3\connectionpool.py", line 672, in urlopen
  File "lib\site-packages\urllib3\connectionpool.py", line 376, in _make_request
  File "lib\site-packages\urllib3\connectionpool.py", line 994, in _validate_conn
  File "lib\site-packages\urllib3\connection.py", line 360, in connect
  File "lib\site-packages\urllib3\util\ssl_.py", line 370, in ssl_wrap_socket
  File "ssl.py", line 407, in wrap_socket
  File "ssl.py", line 817, in __init__
  File "ssl.py", line 1077, in do_handshake
  File "ssl.py", line 689, in do_handshake
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib\site-packages\requests\adapters.py", line 449, in send
  File "lib\site-packages\urllib3\connectionpool.py", line 720, in urlopen
  File "lib\site-packages\urllib3\util\retry.py", line 400, in increment
  File "lib\site-packages\urllib3\packages\six.py", line 734, in reraise
  File "lib\site-packages\urllib3\connectionpool.py", line 672, in urlopen
  File "lib\site-packages\urllib3\connectionpool.py", line 376, in _make_request
  File "lib\site-packages\urllib3\connectionpool.py", line 994, in _validate_conn
  File "lib\site-packages\urllib3\connection.py", line 360, in connect
  File "lib\site-packages\urllib3\util\ssl_.py", line 370, in ssl_wrap_socket
  File "ssl.py", line 407, in wrap_socket
  File "ssl.py", line 817, in __init__
  File "ssl.py", line 1077, in do_handshake
  File "ssl.py", line 689, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "user_sync\app.py", line 188, in sync
  File "user_sync\app.py", line 422, in begin_work
  File "user_sync\post_sync\manager.py", line 33, in run
  File "user_sync\post_sync\connectors\sign_sync\__init__.py", line 53, in run
  File "user_sync\post_sync\connectors\sign_sync\__init__.py", line 56, in update_sign_users
  File "user_sync\post_sync\connectors\sign_sync\client.py", line 108, in get_users
  File "lib\site-packages\requests\api.py", line 76, in get
  File "lib\site-packages\requests\api.py", line 61, in request
  File "lib\site-packages\requests\sessions.py", line 530, in request
  File "lib\site-packages\requests\sessions.py", line 643, in send
  File "lib\site-packages\requests\adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
```

**Steps to reproduce**
usual config setting are used
* Command-line options used
 not impacting sign connector, but here they are: --process-groups --users mapped
* Specific details around identity source, group mapping, etc.
the group that syncs to Sign contains ~ 2500 accounts

**Expected behavior**
Sync job ends successfully without errors

**Screenshots**

**Environment**
 - UST version: 2.6.0
 - OS type and version: Windows
 - Any other relevant info: runs on scheduled task once per day, but to obtain last log a manual run in debug level mode was used

**Comment by vossen-adobe** [comment]
These kind of errors are also often caused by the client networking environment.  Unfortunately very difficult to track down where the connection is being interrupted.

**Comment by adorton-adobe** [comment]
I'll take a look. My guess is that either the Sign API does not have request throttling or that we are not using it.

**Comment by Luci2015** [comment]
According to [this](https://www.adobe.io/apis/documentcloud/sign/docs.html#!adobedocs/adobe-sign/master/api_usage/throttling.md) older document, Sign does throttle but the limits are variable, depending on other factors.
If it would've been throttling, I would've seen a blocking "Error retrieving..." mesage in the log  because of HTTP code being different than 200 ( if I got correctly that bit of code).

Also, is there really no API for bulk extraction or paginated extraction of users?

**Comment by adorton-adobe** [comment]
That doc refers to v6, and we have to use v5 for its account provisioning features. I'll reach out to Sign engineering and find out if v5 does anything differently with regard to throttling.

We can get a list of all users, but the UserInfo object it returns for each users does not contain the user's account status or admin roles, which we need in the sync workflow. We need to query each user individually for that information.

See https://secure.na1.echosign.com/public/docs/restapi/v5#!/users/getUsers

**Comment by adorton-adobe** [comment]
Closing this since based on internal discussion, it may be an issue with the customer network. @Luci2015 please re-open if there is more to investigate on the UST or Sign API side.

**Comment by madumro** [comment]
Could this issue be re-opened? It would help setting a timeout for the Sign API endpoint and at least 2 attempts before closing the connection. At this moment Sign endpoint breaks the connection directly. This issue can be replicated if there are more Sign users to be retrieved. 
Thanks!

**Comment by vossen-adobe** [comment]
@adorton-adobe this may be a scaling issue we should look into, as it seems to be happening now that the user count is climbing
