### ISSUE TITLE
Adobe only user list broken with post sync

### ISSUE THREAD

**Issue by mbonish** [adobe-apiplatform/user-sync.py#638]
If Adobe only user list is used with user sync 2.6 (current version) a nonetype exception is thrown because the umapi post sync data fails to handle this case properly

**Comment by cbalanoiu** [comment]
This is not just with post-sync. I get the error also when simply trying to delete some users:
user-sync.exe --adobe-only-user-list remove-list.csv --adobe-only-user-action remove
...
2020-09-28 08:12:42 2060 INFO processor - ---------- Start Sync with UMAPI ---------------------------
2020-09-28 08:12:42 2060 DEBUG processor - Processing Adobe-only users...
2020-09-28 08:12:42 2060 INFO processor - Removing Adobe-only user: federatedID,user3,cbart.ro
2020-09-28 08:12:42 2060 ERROR main - Unhandled exception
Traceback (most recent call last):
  File "user_sync\app.py", line 186, in sync
  File "user_sync\app.py", line 416, in begin_work
  File "user_sync\rules.py", line 201, in run
  File "user_sync\rules.py", line 600, in process_strays
  File "user_sync\rules.py", line 674, in manage_strays
  File "user_sync\post_sync\manager.py", line 86, in remove_umapi_user
TypeError: argument of type 'NoneType' is not iterable

The last version this works in is 2.5.1.

**Comment by vossen-adobe** [comment]
This is resolved by the bugfix mentioned above - it hasn't been merged yet though I think it is ready

**Comment by n8felton** [comment]
I noticed this was added to the v2.6.2 milestone, but I am curious if there was any kind of planned release date. I'm running into this bug now and it's preventing me from processing user removals from our admin console.

**Comment by vossen-adobe** [comment]
I'll let @adorton-adobe  comment on release - but if you need to do a removal, can you roll back to 2.5 temporarily?
