### ISSUE TITLE
Creating Adobe side users from a different email ldap attribute

### ISSUE THREAD

**Issue by cojocarule** [adobe-apiplatform/user-sync.py#750]
Hello,

I'm trying to use extension mapping in order to read a secondary mail attribute from ldap and when this exists,  create the Adobe side users with this value as email and username. 

My extension-config looks like this:

```
#
extended_attributes:
  - c
  - CloudMail
  
extended_adobe_groups: []

after_mapping_hook: |
    ct = source_attributes.get('c')
    cloudmail = source_attributes.get('CloudMail')
    if ct.lower() == 'im' or ct.lower() == 'gg' or ct.lower() == 'je':
      target_attributes['country'] = 'US'
    if cloudmail:
      target_attributes['username'] = cloudmail
      target_attributes['email'] = cloudmail
```

This works, in that i can see the before/after values changing accordingly, but then towards the end of the UMAPI sync thsi error appears, any suggestions?

```
2021-11-26 12:31:21 9300 ERROR main - Unhandled exception
Traceback (most recent call last):
  File "user_sync\app.py", line 193, in sync
  File "user_sync\app.py", line 462, in begin_work
  File "user_sync\rules.py", line 199, in run
  File "user_sync\rules.py", line 502, in sync_umapi_users
  File "user_sync\rules.py", line 792, in create_umapi_user
  File "user_sync\rules.py", line 737, in create_umapi_commands_for_directory_user
  File "user_sync\rules.py", line 1028, in is_adobeID_email_exist
  File "user_sync\helper.py", line 41, in normalize_string
AttributeError: 'list' object has no attribute 'strip'
2021-11-26 12:31:21 9300 INFO main - ========== End Run (User Sync version: 2.6.3) (Total time: 1:37:16) ==
```

**Comment by Luci2015** [comment]
It's possible that the attribute CloudMail returns values in a format of a list insteaf of a string.
If that is the case, if there are multiple values in there you will need to settle on one of the values in the list. The one you settle will be dicated by the code you will use to determine which one suits best your need.
For example, if you want the first value in the list, you would go with index 0:
```
    if cloudmail:
      target_attributes['username'] = cloudmail[0]
      target_attributes['email'] = cloudmail[0]
```
If first value is not suitable add code to verify if it's the one you need (for ex ending in some domain, contains some string you are expecting, etc..)

Have a test and feedback

**Comment by cojocarule** [comment]
Yes, It's working like this. 
Thank you!

**Comment by adorton-adobe** [comment]
Closing this since it seems resolved.
