### ISSUE TITLE
Unhandled exception - for a particular group.

### ISSUE THREAD

**Issue by cojocarule** [adobe-apiplatform/user-sync.py#751]
Hello,

I have a situation that when I add a particular ldap group in the group mapping, It always returns an unhabdled exception like in the log output bellow. The directory reading part is working fine in that the existing group users are read but when the script gets to the UMAPI  sync, the bellow error is thrown. 
All other mapped groups work once I remove this particular one from the config. 

user-sync-config.yml

```
    - directory_group: "Adobe_Acrobat_Users_JP"
       adobe_groups:
            - "Adobe_Acrobat_Users_JP"
```

Log output:

2021-11-29 08:16:06 4280 DEBUG umapi - Ran user query: ['Adobe_Acrobat_Users_JP'] {'directOnly': True} (0 found)
2021-11-29 08:16:06 4280 ERROR main - Unhandled exception
Traceback (most recent call last):
  File "user_sync\app.py", line 193, in sync
  File "user_sync\app.py", line 462, in begin_work
  File "user_sync\rules.py", line 199, in run
  File "user_sync\rules.py", line 487, in sync_umapi_users
  File "user_sync\rules.py", line 915, in update_umapi_users_for_connector
  File "user_sync\connector\umapi.py", line 129, in iter_users
  File "umapi_client\api.py", line 240, in __next__
  File "umapi_client\api.py", line 236, in next
  File "umapi_client\api.py", line 220, in _next_item
  File "umapi_client\api.py", line 211, in _next_page
ValueError: not enough values to unpack (expected 6, got 2)
2021-11-29 08:16:06 4280 INFO main - ========== End Run (User Sync version: 2.6.3) (Total time: 0:02:18) ==

**Comment by adorton-adobe** [comment]
2.6.3 is not a supported release. Please upgrade to the [latest ](https://github.com/adobe-apiplatform/user-sync.py/releases/latest) stable version and see if that resolves the issue.

**Comment by adorton-adobe** [comment]
Hello - did that resolve the error? Can I close this issue?

**Comment by cojocarule** [comment]
Hi, yes this can be closed. 
I havn't tried with the newer version, but manually creating the group on the Adobe Console before running the sync tool worked.

**Comment by bhunut-adobe** [comment]
I was able to verify the error. Updated to Version 2.7.0 resolved the issue.
