### ISSUE TITLE
Module Not Found Error: No module named Sqlite_3****

### ISSUE THREAD

**Issue by tpegues2** [adobe-apiplatform/user-sync.py#763]
**Description**
When I run ./user-sync version 2.7 for centos7 on Redhat7 it fails right away.

**Steps to reproduce**
* Relevant config options
* Command-line options used
* Specific details around identity source, group mapping, etc.

**Expected behavior**

I expected that it will simply give me the version number.  

**Screenshots**
[tpegues2@ausyncprdapp ~]$ ./user-sync -v
Traceback (most recent call last):
  File "user_sync/app.py", line 37, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 476, in exec_module
  File "user_sync/config/sign_sync.py", line 14, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 476, in exec_module
  File "user_sync/engine/sign.py", line 7, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 476, in exec_module
  File "user_sync/connector/connector_sign.py", line 26, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 476, in exec_module
  File "user_sync/cache/sign/__init__.py", line 1, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 476, in exec_module
  File "user_sync/cache/sign/cache.py", line 1, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 476, in exec_module
  File "user_sync/cache/base.py", line 2, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 476, in exec_module
  File "sqlite3/__init__.py", line 23, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 476, in exec_module
  File "sqlite3/dbapi2.py", line 27, in <module>
ModuleNotFoundError: No module named '_sqlite3'
[19788] Failed to execute script 'app' due to unhandled exception!

**Environment**
 - UST version:
 - OS type and version: RedHat 7.9 and user-sync version 2.70
 - Any other relevant info:

**Comment by jnw-vw** [comment]
Unfortunately, I'm still experiencing this issue on RedHat Enterprise Linux 8 even with user-sync-v2.7.3-centos:
```
$ /appl/aemusersync/user-sync  -c /appl/aemusersync/config/user-sync-config.yml
Traceback (most recent call last):
  File "user_sync/app.py", line 37, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "user_sync/config/sign_sync.py", line 14, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "user_sync/engine/sign.py", line 7, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "user_sync/connector/connector_sign.py", line 26, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "user_sync/cache/sign/__init__.py", line 1, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "user_sync/cache/sign/cache.py", line 1, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "user_sync/cache/base.py", line 2, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "sqlite3/__init__.py", line 23, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "sqlite3/dbapi2.py", line 27, in <module>
ModuleNotFoundError: No module named '_sqlite3'
[1129804] Failed to execute script 'app' due to unhandled exception!
```
```
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.5 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.5 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.5
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.5"
```

**Comment by jnw-vw** [comment]
@adorton-adobe can you reopen this issue or should we report a new one?

**Comment by adorton-adobe** [comment]
I'm looking into it.

**Comment by adorton-adobe** [comment]
@jnw-vw When it is convenient, will you give this build a try and let me know if it resolves the issue?

[user-sync-centos-fix.zip](https://github.com/adobe-apiplatform/user-sync.py/files/8427848/user-sync-centos-fix.zip)

**Comment by jnw-vw** [comment]
@adorton-adobe Yes, I tested and your build is working fine for me. 👍

**Comment by adorton-adobe** [comment]
Excellent, thank you for taking a look. I'm going to do some additional testing and will plan to replace the 2.7.3 CentOS binaries on the release. I'll post a note here when I've done that.

**Comment by tpegues2** [comment]
Thank you!!

Sent from my iPhone

On Apr 6, 2022, at 11:20 AM, Andrew Dorton ***@***.***> wrote:

﻿

Excellent, thank you for taking a look. I'm going to do some additional testing and will plan to replace the 2.7.3 CentOS binaries on the release. I'll post a note here when I've done that.

—
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fadobe-apiplatform%2Fuser-sync.py%2Fissues%2F763%23issuecomment-1090395696&data=04%7C01%7Ctpegues2%40kennesaw.edu%7C639999ba86d44986367808da17e0f89c%7C45f26ee5f134439ebc93e6c7e33d61c2%7C1%7C0%7C637848552263260587%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3543F9Z4Jndso3E8Iebf9D6kQ%2BBf3xTChNd6YKnC5LI%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKCBRHUE34ZFJOXG7F46BM3VDWTTPANCNFSM5M6TDOAA&data=04%7C01%7Ctpegues2%40kennesaw.edu%7C639999ba86d44986367808da17e0f89c%7C45f26ee5f134439ebc93e6c7e33d61c2%7C1%7C0%7C637848552263260587%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2Bo2zD8BDKE2g2ZNWITfZIrc%2FAkavpUO6ZBWzyJ7nBVI%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>



CAUTION: This email originated from outside of KSU. Use caution replying or supplying information, clicking links, or opening attachments. If you suspect the message is fraudulent, report it using the Phishing Alert Button<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuits.kennesaw.edu%2Focs%2Fphish-market%2Freport.php&data=04%7C01%7Ctpegues2%40kennesaw.edu%7C639999ba86d44986367808da17e0f89c%7C45f26ee5f134439ebc93e6c7e33d61c2%7C1%7C0%7C637848552263260587%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=7Ny%2FprQQKjVzISgGHi1aBVOO3CJwexBKEBdm4fD2%2BDM%3D&reserved=0> or forward the message to ***@***.******@***.***>.

**Comment by adorton-adobe** [comment]
I've updated the binaries on the latest release. Let me know if you still experience any problems.
