### ISSUE TITLE
Unhandled error in sign-sync: "aiohttp.client_exceptions.ServerTimeoutError: Timeout on reading data from socket"

### ISSUE THREAD

**Issue by madumro** [adobe-apiplatform/user-sync.py#770]
**Description**
sign-sync stops with the following error: 
aiohttp.client_exceptions.ServerTimeoutError: Timeout on reading data from socket

**Steps to reproduce**
* Trying to configure sign-sync with ldap source
* Command-line for testing: user-sync sign-sync -t

**Expected behavior**
Execute the script successfully

**Result**
2022-02-20 23:16:19 23148 DEBUG sign_primary - Attempt 1 to call: https://api.eu1.documents.adobe.com/api/rest/v6/users?pageSize=1000&cursor=3AAABLblqZhASoM3ri...**
2022-02-20 23:18:22 23148 ERROR main - Unhandled exception
Traceback (most recent call last):
  File "user_sync\app.py", line 443, in run_sync
  File "user_sync\app.py", line 337, in begin_work_sign
  File "user_sync\engine\sign.py", line 92, in run
  File "user_sync\engine\sign.py", line 78, in get_groups
  File "user_sync\connector\connector_sign.py", line 67, in sign_groups
  File "user_sync\connector\connector_sign.py", line 139, in refresh_all
  File "user_sync\connector\connector_sign.py", line 146, in refresh_users
  File "sign_client\client.py", line 116, in get_users
  File "sign_client\client.py", line 97, in _paginate_get
  File "sign_client\client.py", line 316, in call_with_retry_sync
  File "asyncio\base_events.py", line 642, in run_until_complete
  File "sign_client\client.py", line 340, in call_with_retry_async
  File "aiohttp\client_reqrep.py", line 1080, in text
  File "aiohttp\client_reqrep.py", line 1036, in read
  File "aiohttp\streams.py", line 375, in read
  File "aiohttp\streams.py", line 397, in readany
  File "aiohttp\streams.py", line 304, in _wait
aiohttp.client_exceptions.ServerTimeoutError: Timeout on reading data from socket
2022-02-20 23:18:22 23148 INFO main - ========== End Run (User Sync version: 2.7.0) (TEST MODE) (Total time: 0:04:25) 

**Environment**
 - UST version: 2.7.0
 - OS type and version: Windows 10.0.19042
 - Any other relevant info: the issue seems to be intermittent

**Comment by adorton-adobe** [comment]
How often would you say you see this error? Does it happen every time sync is run?

**Comment by adorton-adobe** [comment]
Let me know if you're still seeing this.

**Comment by madumro** [comment]
This error was generated at the first run of the sign-sync tool, when there was no cache and the Sign API had to interrogate all the Sign users. In this case there were ~7500 active users. However, the subsequent executions succeeded.

**Comment by adorton-adobe** [comment]
It is most likely an intermittent service outage, but the UST should handle it like regular throttling. I'll get this fix on the backlog.
