### ISSUE TITLE
Sign Sync fails due to API response

### ISSUE THREAD

**Issue by kmacleanuosa** [adobe-apiplatform/user-sync.py#829]
Getting groups for Sign users fails due to Sign API response, `canUseMulticastWorkflows` is not of the same form as existing settings.
Issue started around 2023-11-14 06:04:07 GMT

```
INFO sign_primary - Getting groups for 23 Sign users
DEBUG sign_primary - Attempt 1 to call: https://api.eu2.adobesign.com/api/rest/v6/users/user_id/groups
future: <Task finished name='Task-67' coro=<SignClient._get_user_groups() done, defined at sign_client\client.py:277> exception=TypeError('sign_client.model.BooleanSettingsInfo() argument after ** must be a mapping, not bool')>
Traceback (most recent call last):
  File "sign_client\client.py", line 284, in _get_user_groups
  File "sign_client\model.py", line 211, in from_dict
  File "sign_client\model.py", line 211, in <listcomp>
  File "sign_client\model.py", line 199, in from_dict
  File "sign_client\model.py", line 180, in from_dict
  File "sign_client\model.py", line 180, in <dictcomp>
  File "sign_client\model.py", line 165, in from_dict
TypeError: sign_client.model.BooleanSettingsInfo() argument after ** must be a mapping, not bool
```
Formatted response from API endpoint:
```json
{
    "groupInfoList": [
        {
            "status": "ACTIVE",
            "id": "user_id",
            "createdDate": "2022-05-18T10:35:13Z",
            "isGroupAdmin": false,
            "isPrimaryGroup": true,
            "name": "Default Group",
            "settings": {
                "userCanSend": {
                    "value": true,
                    "inherited": true
                },
                "canUseMulticastWorkflows": true,
                "libaryDocumentCreationVisible": {
                    "value": true,
                    "inherited": true
                },
                "sendRestrictedToWorkflows": {
                    "value": false
                },
                "userManagedWorkflowsEnabled": {
                    "value": true
                },
                "allowedToShareUserCreatedWorkflows": {
                    "value": false
                },
                "widgetCreationVisible": {
                    "value": true
                }
            }
        }
    ]
}
```

**Comment by kmacleanuosa** [comment]
closing as noted https://github.com/adobe-apiplatform/user-sync.py/pull/831#issuecomment-1871463069 in #831 from #830 this was resolved by Sign Engineering
