### ISSUE TITLE
Sign sync is failing

### ISSUE THREAD

**Issue by Luci2015** [adobe-apiplatform/user-sync.py#830]
**Description**
Sign sync started to fail with this message: 
`TypeError: sign_client.model.BooleanSettingsInfo() argument after ** must be a mapping, not bool`

```
2023-11-20 09:23:19 43895 ERROR asyncio - Task exception was never retrieved
future: <Task finished name='Task-86' coro=<SignClient._get_user_groups() done, defined at /Users/user/user-sync.py-2.10.0rc1/ENV/lib/python3.10/site-packages/sign_client/client.py:277> exception=TypeError('sign_client.model.BooleanSettingsInfo() argument after ** must be a mapping, not bool')>
Traceback (most recent call last):
  File "/Users/user/user-sync.py-2.10.0rc1/ENV/lib/python3.10/site-packages/sign_client/client.py", line 284, in _get_user_groups
    groups = UserGroupsInfo.from_dict(groups)
  File "/Users/user/user-sync.py-2.10.0rc1/ENV/lib/python3.10/site-packages/sign_client/model.py", line 211, in from_dict
    return cls([UserGroupInfo.from_dict(v) for v in dct['groupInfoList']])
  File "/Users/user/user-sync.py-2.10.0rc1/ENV/lib/python3.10/site-packages/sign_client/model.py", line 211, in <listcomp>
    return cls([UserGroupInfo.from_dict(v) for v in dct['groupInfoList']])
  File "/Users/user/user-sync.py-2.10.0rc1/ENV/lib/python3.10/site-packages/sign_client/model.py", line 199, in from_dict
    new_dct[k] = SettingsInfo.from_dict(v)
  File "/Users/user/user-sync.py-2.10.0rc1/ENV/lib/python3.10/site-packages/sign_client/model.py", line 180, in from_dict
    new_dct = {k: BooleanSettingsInfo.from_dict(v) for k, v in dct.items()}
  File "/Users/user/user-sync.py-2.10.0rc1/ENV/lib/python3.10/site-packages/sign_client/model.py", line 180, in <dictcomp>
    new_dct = {k: BooleanSettingsInfo.from_dict(v) for k, v in dct.items()}
  File "/Users/user/user-sync.py-2.10.0rc1/ENV/lib/python3.10/site-packages/sign_client/model.py", line 165, in from_dict
    return cls(**dct)
TypeError: sign_client.model.BooleanSettingsInfo() argument after ** must be a mapping, not bool
```

**Steps to reproduce**
* run UST with sign-sync option as usual

**Expected behavior**
no failure during sync

**Environment**
 - UST version: latest
 - OS type and version: all

**Comment by adorton-adobe** [comment]
I believe this was resolved as per #831
